ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJpdGVtQWN0aW9uIjoiVmlldyBJdGVtIiwiY2F0YWxvZyI6eyJJdGVtQ2xhc3MiOnsiX2lkIjoib3ZlcnZpZXcifX0sInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiMTgzNjI0NTg2OC4xNzQ1NDQwOTkyIn0sImFub25JZCI6IjI4MjQ5Njc2MWY3N2Q1YTkifSwic291cmNlIjp7InVybCI6Imh0dHBzOi8vd3d3Lm1lcmNlZGVzLWJlbnouaXQvcGFzc2VuZ2VyY2Fycy9tb2RlbHMvY291cGUvY2xlL292ZXJ2aWV3Lmh0bWwiLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjYzIiwiY29udGVudFpvbmVzIjpbXX0sImNvbnNlbnRzIjpbXSwiYWNjb3VudCI6e30sIl90b29sc0V2ZW50TGlua0lkIjoiOTY5MzczODIyMzc2Mzk5NyIsImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX19: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x5580c0353cea <unknown>
#1 0x5580bfe045f0 <unknown>
#2 0x5580bfdeae86 <unknown>
#3 0x5580bfde979a <unknown>
#4 0x5580bfde9eff <unknown>
#5 0x5580bfde9e54 <unknown>
#6 0x5580bfe087ff <unknown>
#7 0x5580bfead9aa <unknown>
#8 0x5580bfe7b662 <unknown>
#9 0x5580bfea1660 <unknown>
#10 0x5580bfe7b433 <unknown>
#11 0x5580bfe47ea3 <unknown>
#12 0x5580bfe48b01 <unknown>
#13 0x5580c0318b3b <unknown>
#14 0x5580c031ca21 <unknown>
#15 0x5580c02ffc32 <unknown>
#16 0x5580c031d594 <unknown>
#17 0x5580c02e3eef <unknown>
#18 0x5580c0341d98 <unknown>
#19 0x5580c0341f76 <unknown>
#20 0x5580c0352b36 <unknown>
#21 0x7fc1c9e9caa4 <unknown>
#22 0x7fc1c9f29c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJQcm9kdWN0IEluZm9ybWF0aW9uIFBhZ2UgLSBvdmVydmlldyAyMzYzIiwiaXRlbUFjdGlvbiI6IlZpZXcgSXRlbSIsInNvdXJjZSI6eyJwYWdlVHlwZSI6InByb2R1Y3RfaW5mb3JtYXRpb24iLCJsb2NhbGUiOiJpdF9JVCIsImNvbnRlbnRab25lcyI6WyJnbG9iYWxfUElfTkwiLCJwaV9iYW5uZXJfTkwiLCJlcXMtc3BlY2lhbF9OTCJdLCJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL2NvdXBlL2NsZS9vdmVydmlldy5odG1sIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI2MyJ9LCJmbGFncyI6eyJwYWdlVmlldyI6dHJ1ZX0sInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiMTgzNjI0NTg2OC4xNzQ1NDQwOTkyIn0sImFub25JZCI6IjI4MjQ5Njc2MWY3N2Q1YTkifSwicGVyZm9ybWFuY2UiOnt9LCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9LCJjYXRhbG9nIjp7IlByb2R1Y3QiOnsiX2lkIjoiMjM2MyIsImRpbWVuc2lvbnMiOnsiQmF1bXVzdGVyU2hvcnQiOlsiMjM2MyJdfX19LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJfdG9vbHNFdmVudExpbmtJZCI6IjA1ODQ3NzAzMTk5NDY2MjM2NSJ9: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x5580c0353cea <unknown>
#1 0x5580bfe045f0 <unknown>
#2 0x5580bfdeae86 <unknown>
#3 0x5580bfde979a <unknown>
#4 0x5580bfde9eff <unknown>
#5 0x5580bfde9e54 <unknown>
#6 0x5580bfe087ff <unknown>
#7 0x5580bfead9aa <unknown>
#8 0x5580bfe7b662 <unknown>
#9 0x5580bfea1660 <unknown>
#10 0x5580bfe7b433 <unknown>
#11 0x5580bfe47ea3 <unknown>
#12 0x5580bfe48b01 <unknown>
#13 0x5580c0318b3b <unknown>
#14 0x5580c031ca21 <unknown>
#15 0x5580c02ffc32 <unknown>
#16 0x5580c031d594 <unknown>
#17 0x5580c02e3eef <unknown>
#18 0x5580c0341d98 <unknown>
#19 0x5580c0341f76 <unknown>
#20 0x5580c0352b36 <unknown>
#21 0x7fc1c9e9caa4 <unknown>
#22 0x7fc1c9f29c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gb3ZlcnZpZXciLCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjE4MzYyNDU4NjguMTc0NTQ0MDk5MiJ9LCJhbm9uSWQiOiIyODI0OTY3NjFmNzdkNWE5In0sInNvdXJjZSI6eyJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL2NvdXBlL2NsZS9vdmVydmlldy5odG1sIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI2MyIsImNvbnRlbnRab25lcyI6W119LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJfdG9vbHNFdmVudExpbmtJZCI6IjQ4OTUzNzkwMDA4NTY0ODciLCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9fQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x5580c0353cea <unknown>
#1 0x5580bfe045f0 <unknown>
#2 0x5580bfdeae86 <unknown>
#3 0x5580bfde979a <unknown>
#4 0x5580bfde9eff <unknown>
#5 0x5580bfde9e54 <unknown>
#6 0x5580bfe087ff <unknown>
#7 0x5580bfead9aa <unknown>
#8 0x5580bfe7b662 <unknown>
#9 0x5580bfea1660 <unknown>
#10 0x5580bfe7b433 <unknown>
#11 0x5580bfe47ea3 <unknown>
#12 0x5580bfe48b01 <unknown>
#13 0x5580c0318b3b <unknown>
#14 0x5580c031ca21 <unknown>
#15 0x5580c02ffc32 <unknown>
#16 0x5580c031d594 <unknown>
#17 0x5580c02e3eef <unknown>
#18 0x5580c0341d98 <unknown>
#19 0x5580c0341f76 <unknown>
#20 0x5580c0352b36 <unknown>
#21 0x7fc1c9e9caa4 <unknown>
#22 0x7fc1c9f29c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJzZXRfdXNlcl9hdHRyaWJ1dGUiLCJhY2NvdW50Ijp7ImF0dHJpYnV0ZXMiOnsibGFzdFBpUGFnZSI6eyJ2ZWhpY2xlUEkiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL2NvdXBlL2NsZS9vdmVydmlldy5odG1sIiwidmVoaWNsZUNvZGUiOiJjMjM2IiwidmVoaWNsZUJNIjoiMjM2MyIsInZlaGljbGVQSUhpc3RvcnkiOiIyMzYzIiwidGltZXN0YW1wIjoxNzQ1NDQwOTk2MDc2LCJleHBpcmF0aW9uIjoxMjB9fX0sInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiMTgzNjI0NTg2OC4xNzQ1NDQwOTkyIn0sImFub25JZCI6IjI4MjQ5Njc2MWY3N2Q1YTkifSwic291cmNlIjp7InVybCI6Imh0dHBzOi8vd3d3Lm1lcmNlZGVzLWJlbnouaXQvcGFzc2VuZ2VyY2Fycy9tb2RlbHMvY291cGUvY2xlL292ZXJ2aWV3Lmh0bWwiLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjYzIiwiY29udGVudFpvbmVzIjpbXX0sImNvbnNlbnRzIjpbXSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiIxNTM0MzUwODk1NzYyNzA3MiIsImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX19: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x5580c0353cea <unknown>
#1 0x5580bfe045f0 <unknown>
#2 0x5580bfdeae86 <unknown>
#3 0x5580bfde979a <unknown>
#4 0x5580bfde9eff <unknown>
#5 0x5580bfde9e54 <unknown>
#6 0x5580bfe087ff <unknown>
#7 0x5580bfead9aa <unknown>
#8 0x5580bfe7b662 <unknown>
#9 0x5580bfea1660 <unknown>
#10 0x5580bfe7b433 <unknown>
#11 0x5580bfe47ea3 <unknown>
#12 0x5580bfe48b01 <unknown>
#13 0x5580c0318b3b <unknown>
#14 0x5580c031ca21 <unknown>
#15 0x5580c02ffc32 <unknown>
#16 0x5580c031d594 <unknown>
#17 0x5580c02e3eef <unknown>
#18 0x5580c0341d98 <unknown>
#19 0x5580c0341f76 <unknown>
#20 0x5580c0352b36 <unknown>
#21 0x7fc1c9e9caa4 <unknown>
#22 0x7fc1c9f29c3c <unknown>

ERROR    root:VerifyPersonalizationAndCapture.py:18 ‚ùå Error attaching screenshot to Allure: [Errno 2] No such file or directory: '/home/runner/work/QA-App-Allure/QA-App-Allure/Tests/BFV1_attempt_1.png'