ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJpdGVtQWN0aW9uIjoiVmlldyBJdGVtIiwiY2F0YWxvZyI6eyJJdGVtQ2xhc3MiOnsiX2lkIjoib3ZlcnZpZXcifX0sInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiMTQxOTg1NTgxNi4xNzQ1NDgwNDI1In0sImFub25JZCI6IjUxYTkzMTRlMzcxODkxNWQifSwic291cmNlIjp7InVybCI6Imh0dHBzOi8vd3d3Lm1lcmNlZGVzLWJlbnouaXQvcGFzc2VuZ2VyY2Fycy9tb2RlbHMvc3V2L2dsZS9vdmVydmlldy5odG1sIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI2MyIsImNvbnRlbnRab25lcyI6W119LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJfdG9vbHNFdmVudExpbmtJZCI6IjE0MTE4MTk4NzA4NjY5NzE2IiwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfX0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x556c43584cea <unknown>
#1 0x556c430355f0 <unknown>
#2 0x556c4301be86 <unknown>
#3 0x556c4301a79a <unknown>
#4 0x556c4301aeff <unknown>
#5 0x556c4301ae54 <unknown>
#6 0x556c430397ff <unknown>
#7 0x556c430de9aa <unknown>
#8 0x556c430ac662 <unknown>
#9 0x556c430d2660 <unknown>
#10 0x556c430ac433 <unknown>
#11 0x556c43078ea3 <unknown>
#12 0x556c43079b01 <unknown>
#13 0x556c43549b3b <unknown>
#14 0x556c4354da21 <unknown>
#15 0x556c43530c32 <unknown>
#16 0x556c4354e594 <unknown>
#17 0x556c43514eef <unknown>
#18 0x556c43572d98 <unknown>
#19 0x556c43572f76 <unknown>
#20 0x556c43583b36 <unknown>
#21 0x7f3f3169caa4 <unknown>
#22 0x7f3f31729c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gb3ZlcnZpZXciLCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjE0MTk4NTU4MTYuMTc0NTQ4MDQyNSJ9LCJhbm9uSWQiOiI1MWE5MzE0ZTM3MTg5MTVkIn0sInNvdXJjZSI6eyJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9nbGUvb3ZlcnZpZXcuaHRtbCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjMiLCJjb250ZW50Wm9uZXMiOltdfSwiY29uc2VudHMiOltdLCJhY2NvdW50Ijp7fSwicGVyZm9ybWFuY2UiOnsic2RrUGFyc2VUaW1lIjoxfSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiI4MjQ2MTA0NzczODMxNjA4IiwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfX0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x556c43584cea <unknown>
#1 0x556c430355f0 <unknown>
#2 0x556c4301be86 <unknown>
#3 0x556c4301a79a <unknown>
#4 0x556c4301aeff <unknown>
#5 0x556c4301ae54 <unknown>
#6 0x556c430397ff <unknown>
#7 0x556c430de9aa <unknown>
#8 0x556c430ac662 <unknown>
#9 0x556c430d2660 <unknown>
#10 0x556c430ac433 <unknown>
#11 0x556c43078ea3 <unknown>
#12 0x556c43079b01 <unknown>
#13 0x556c43549b3b <unknown>
#14 0x556c4354da21 <unknown>
#15 0x556c43530c32 <unknown>
#16 0x556c4354e594 <unknown>
#17 0x556c43514eef <unknown>
#18 0x556c43572d98 <unknown>
#19 0x556c43572f76 <unknown>
#20 0x556c43583b36 <unknown>
#21 0x7f3f3169caa4 <unknown>
#22 0x7f3f31729c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJQcm9kdWN0IEluZm9ybWF0aW9uIFBhZ2UgLSBvdmVydmlldyAxNjcxIiwiaXRlbUFjdGlvbiI6IlZpZXcgSXRlbSIsInNvdXJjZSI6eyJwYWdlVHlwZSI6InByb2R1Y3RfaW5mb3JtYXRpb24iLCJsb2NhbGUiOiJpdF9JVCIsImNvbnRlbnRab25lcyI6WyJnbG9iYWxfUElfTkwiLCJwaV9iYW5uZXJfTkwiLCJlcXMtc3BlY2lhbF9OTCJdLCJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9nbGUvb3ZlcnZpZXcuaHRtbCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjMifSwiZmxhZ3MiOnsicGFnZVZpZXciOnRydWV9LCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjE0MTk4NTU4MTYuMTc0NTQ4MDQyNSJ9LCJhbm9uSWQiOiI1MWE5MzE0ZTM3MTg5MTVkIn0sInBlcmZvcm1hbmNlIjp7InNka1BhcnNlVGltZSI6MX0sImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX0sImNhdGFsb2ciOnsiUHJvZHVjdCI6eyJfaWQiOiIxNjcxIiwiZGltZW5zaW9ucyI6eyJCYXVtdXN0ZXJTaG9ydCI6WyIxNjcxIl19fX0sImNvbnNlbnRzIjpbXSwiYWNjb3VudCI6e30sIl90b29sc0V2ZW50TGlua0lkIjoiMzU2ODgyOTU0Mjc1ODU0MjYifQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x556c43584cea <unknown>
#1 0x556c430355f0 <unknown>
#2 0x556c4301be86 <unknown>
#3 0x556c4301a79a <unknown>
#4 0x556c4301aeff <unknown>
#5 0x556c4301ae54 <unknown>
#6 0x556c430397ff <unknown>
#7 0x556c430de9aa <unknown>
#8 0x556c430ac662 <unknown>
#9 0x556c430d2660 <unknown>
#10 0x556c430ac433 <unknown>
#11 0x556c43078ea3 <unknown>
#12 0x556c43079b01 <unknown>
#13 0x556c43549b3b <unknown>
#14 0x556c4354da21 <unknown>
#15 0x556c43530c32 <unknown>
#16 0x556c4354e594 <unknown>
#17 0x556c43514eef <unknown>
#18 0x556c43572d98 <unknown>
#19 0x556c43572f76 <unknown>
#20 0x556c43583b36 <unknown>
#21 0x7f3f3169caa4 <unknown>
#22 0x7f3f31729c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJzZXRfdXNlcl9hdHRyaWJ1dGUiLCJhY2NvdW50Ijp7ImF0dHJpYnV0ZXMiOnsibGFzdFBpUGFnZSI6eyJ2ZWhpY2xlUEkiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9nbGUvb3ZlcnZpZXcuaHRtbCIsInZlaGljbGVDb2RlIjoidjE2Ny1mbCIsInZlaGljbGVCTSI6IjE2NzEiLCJ2ZWhpY2xlUElIaXN0b3J5IjoiMTY3MSIsInRpbWVzdGFtcCI6MTc0NTQ4MDQzMDQzNSwiZXhwaXJhdGlvbiI6MTIwfX19LCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjE0MTk4NTU4MTYuMTc0NTQ4MDQyNSJ9LCJhbm9uSWQiOiI1MWE5MzE0ZTM3MTg5MTVkIn0sInNvdXJjZSI6eyJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9nbGUvb3ZlcnZpZXcuaHRtbCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjMiLCJjb250ZW50Wm9uZXMiOltdfSwiY29uc2VudHMiOltdLCJfdG9vbHNFdmVudExpbmtJZCI6IjYwMzgyNjE4NjU1OTIwNzQiLCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9fQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x556c43584cea <unknown>
#1 0x556c430355f0 <unknown>
#2 0x556c4301be86 <unknown>
#3 0x556c4301a79a <unknown>
#4 0x556c4301aeff <unknown>
#5 0x556c4301ae54 <unknown>
#6 0x556c430397ff <unknown>
#7 0x556c430de9aa <unknown>
#8 0x556c430ac662 <unknown>
#9 0x556c430d2660 <unknown>
#10 0x556c430ac433 <unknown>
#11 0x556c43078ea3 <unknown>
#12 0x556c43079b01 <unknown>
#13 0x556c43549b3b <unknown>
#14 0x556c4354da21 <unknown>
#15 0x556c43530c32 <unknown>
#16 0x556c4354e594 <unknown>
#17 0x556c43514eef <unknown>
#18 0x556c43572d98 <unknown>
#19 0x556c43572f76 <unknown>
#20 0x556c43583b36 <unknown>
#21 0x7f3f3169caa4 <unknown>
#22 0x7f3f31729c3c <unknown>

ERROR    root:VerifyPersonalizationAndCapture.py:18 ‚ùå Error attaching screenshot to Allure: [Errno 2] No such file or directory: '/home/runner/work/QA-App-Allure/QA-App-Allure/Tests/BFV1_attempt_1.png'