ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJpdGVtQWN0aW9uIjoiVmlldyBJdGVtIiwiY2F0YWxvZyI6eyJJdGVtQ2xhc3MiOnsiX2lkIjoib3ZlcnZpZXcifX0sInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiMTUyNjg4NjMwMi4xNzQ1NDQwNDM0In0sImFub25JZCI6ImNmOGMzNzVmN2ZkOTRmMDIifSwic291cmNlIjp7InVybCI6Imh0dHBzOi8vd3d3Lm1lcmNlZGVzLWJlbnouaXQvcGFzc2VuZ2VyY2Fycy9tb2RlbHMvc3V2L2Vxcy9vdmVydmlldy5odG1sIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI2MyIsImNvbnRlbnRab25lcyI6W119LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJfdG9vbHNFdmVudExpbmtJZCI6IjY3MTMwOTUyMzcyMTA1MjkiLCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9fQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x5573a120ecea <unknown>
#1 0x5573a0cbf5f0 <unknown>
#2 0x5573a0ca5e86 <unknown>
#3 0x5573a0ca479a <unknown>
#4 0x5573a0ca4eff <unknown>
#5 0x5573a0ca4e54 <unknown>
#6 0x5573a0cc37ff <unknown>
#7 0x5573a0d689aa <unknown>
#8 0x5573a0d36662 <unknown>
#9 0x5573a0d5c660 <unknown>
#10 0x5573a0d36433 <unknown>
#11 0x5573a0d02ea3 <unknown>
#12 0x5573a0d03b01 <unknown>
#13 0x5573a11d3b3b <unknown>
#14 0x5573a11d7a21 <unknown>
#15 0x5573a11bac32 <unknown>
#16 0x5573a11d8594 <unknown>
#17 0x5573a119eeef <unknown>
#18 0x5573a11fcd98 <unknown>
#19 0x5573a11fcf76 <unknown>
#20 0x5573a120db36 <unknown>
#21 0x7fd32469caa4 <unknown>
#22 0x7fd324729c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJQcm9kdWN0IEluZm9ybWF0aW9uIFBhZ2UgLSBvdmVydmlldyAyOTY2IiwiaXRlbUFjdGlvbiI6IlZpZXcgSXRlbSIsInNvdXJjZSI6eyJwYWdlVHlwZSI6InByb2R1Y3RfaW5mb3JtYXRpb24iLCJsb2NhbGUiOiJpdF9JVCIsImNvbnRlbnRab25lcyI6WyJnbG9iYWxfUElfTkwiLCJwaV9iYW5uZXJfTkwiLCJlcXMtc3BlY2lhbF9OTCJdLCJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9lcXMvb3ZlcnZpZXcuaHRtbCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjMifSwiZmxhZ3MiOnsicGFnZVZpZXciOnRydWV9LCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjE1MjY4ODYzMDIuMTc0NTQ0MDQzNCJ9LCJhbm9uSWQiOiJjZjhjMzc1ZjdmZDk0ZjAyIn0sInBlcmZvcm1hbmNlIjp7fSwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfSwiY2F0YWxvZyI6eyJQcm9kdWN0Ijp7Il9pZCI6IjI5NjYiLCJkaW1lbnNpb25zIjp7IkJhdW11c3RlclNob3J0IjpbIjI5NjYiXX19fSwiY29uc2VudHMiOltdLCJhY2NvdW50Ijp7fSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiI5NzAzMjM2NTY1MTUzMTg4In0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x5573a120ecea <unknown>
#1 0x5573a0cbf5f0 <unknown>
#2 0x5573a0ca5e86 <unknown>
#3 0x5573a0ca479a <unknown>
#4 0x5573a0ca4eff <unknown>
#5 0x5573a0ca4e54 <unknown>
#6 0x5573a0cc37ff <unknown>
#7 0x5573a0d689aa <unknown>
#8 0x5573a0d36662 <unknown>
#9 0x5573a0d5c660 <unknown>
#10 0x5573a0d36433 <unknown>
#11 0x5573a0d02ea3 <unknown>
#12 0x5573a0d03b01 <unknown>
#13 0x5573a11d3b3b <unknown>
#14 0x5573a11d7a21 <unknown>
#15 0x5573a11bac32 <unknown>
#16 0x5573a11d8594 <unknown>
#17 0x5573a119eeef <unknown>
#18 0x5573a11fcd98 <unknown>
#19 0x5573a11fcf76 <unknown>
#20 0x5573a120db36 <unknown>
#21 0x7fd32469caa4 <unknown>
#22 0x7fd324729c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gb3ZlcnZpZXciLCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjE1MjY4ODYzMDIuMTc0NTQ0MDQzNCJ9LCJhbm9uSWQiOiJjZjhjMzc1ZjdmZDk0ZjAyIn0sInNvdXJjZSI6eyJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9lcXMvb3ZlcnZpZXcuaHRtbCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjMiLCJjb250ZW50Wm9uZXMiOltdfSwiY29uc2VudHMiOltdLCJhY2NvdW50Ijp7fSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiI3NjcyOTc0NjIwNTQyNTMxIiwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfX0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x5573a120ecea <unknown>
#1 0x5573a0cbf5f0 <unknown>
#2 0x5573a0ca5e86 <unknown>
#3 0x5573a0ca479a <unknown>
#4 0x5573a0ca4eff <unknown>
#5 0x5573a0ca4e54 <unknown>
#6 0x5573a0cc37ff <unknown>
#7 0x5573a0d689aa <unknown>
#8 0x5573a0d36662 <unknown>
#9 0x5573a0d5c660 <unknown>
#10 0x5573a0d36433 <unknown>
#11 0x5573a0d02ea3 <unknown>
#12 0x5573a0d03b01 <unknown>
#13 0x5573a11d3b3b <unknown>
#14 0x5573a11d7a21 <unknown>
#15 0x5573a11bac32 <unknown>
#16 0x5573a11d8594 <unknown>
#17 0x5573a119eeef <unknown>
#18 0x5573a11fcd98 <unknown>
#19 0x5573a11fcf76 <unknown>
#20 0x5573a120db36 <unknown>
#21 0x7fd32469caa4 <unknown>
#22 0x7fd324729c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJzZXRfdXNlcl9hdHRyaWJ1dGUiLCJhY2NvdW50Ijp7ImF0dHJpYnV0ZXMiOnsibGFzdFBpUGFnZSI6eyJ2ZWhpY2xlUEkiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9lcXMvb3ZlcnZpZXcuaHRtbCIsInZlaGljbGVDb2RlIjoieDI5NiIsInZlaGljbGVCTSI6IjI5NjYiLCJ2ZWhpY2xlUElIaXN0b3J5IjoiMjk2NiIsInRpbWVzdGFtcCI6MTc0NTQ0MDQzODM5NiwiZXhwaXJhdGlvbiI6MTIwfX19LCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjE1MjY4ODYzMDIuMTc0NTQ0MDQzNCJ9LCJhbm9uSWQiOiJjZjhjMzc1ZjdmZDk0ZjAyIn0sInNvdXJjZSI6eyJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9lcXMvb3ZlcnZpZXcuaHRtbCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjMiLCJjb250ZW50Wm9uZXMiOltdfSwiY29uc2VudHMiOltdLCJfdG9vbHNFdmVudExpbmtJZCI6IjQ2NjMyNTE1MDg4NjA3OTczIiwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfX0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x5573a120ecea <unknown>
#1 0x5573a0cbf5f0 <unknown>
#2 0x5573a0ca5e86 <unknown>
#3 0x5573a0ca479a <unknown>
#4 0x5573a0ca4eff <unknown>
#5 0x5573a0ca4e54 <unknown>
#6 0x5573a0cc37ff <unknown>
#7 0x5573a0d689aa <unknown>
#8 0x5573a0d36662 <unknown>
#9 0x5573a0d5c660 <unknown>
#10 0x5573a0d36433 <unknown>
#11 0x5573a0d02ea3 <unknown>
#12 0x5573a0d03b01 <unknown>
#13 0x5573a11d3b3b <unknown>
#14 0x5573a11d7a21 <unknown>
#15 0x5573a11bac32 <unknown>
#16 0x5573a11d8594 <unknown>
#17 0x5573a119eeef <unknown>
#18 0x5573a11fcd98 <unknown>
#19 0x5573a11fcf76 <unknown>
#20 0x5573a120db36 <unknown>
#21 0x7fd32469caa4 <unknown>
#22 0x7fd324729c3c <unknown>

ERROR    root:VerifyPersonalizationAndCapture.py:18 ‚ùå Error attaching screenshot to Allure: [Errno 2] No such file or directory: '/home/runner/work/QA-App-Allure/QA-App-Allure/Tests/BFV1_attempt_1.png'