ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJpdGVtQWN0aW9uIjoiVmlldyBJdGVtIiwiY2F0YWxvZyI6eyJJdGVtQ2xhc3MiOnsiX2lkIjoib3ZlcnZpZXcifX0sInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiOTgzNjAxMzA5LjE3NDU0MzY3MTkifSwiYW5vbklkIjoiOTdmMDZmOTUxZjM4Zjc1ZiJ9LCJzb3VyY2UiOnsidXJsIjoiaHR0cHM6Ly93d3cubWVyY2VkZXMtYmVuei5pdC9wYXNzZW5nZXJjYXJzL21vZGVscy9zdXYvZ2xjL292ZXJ2aWV3Lmh0bWwiLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjYzIiwiY29udGVudFpvbmVzIjpbXX0sImNvbnNlbnRzIjpbXSwiYWNjb3VudCI6e30sIl90b29sc0V2ZW50TGlua0lkIjoiMDUxMjQyODY4ODk2NTY4NDgiLCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9fQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x560fdd8aecea <unknown>
#1 0x560fdd35f5f0 <unknown>
#2 0x560fdd345e86 <unknown>
#3 0x560fdd34479a <unknown>
#4 0x560fdd344eff <unknown>
#5 0x560fdd344e54 <unknown>
#6 0x560fdd3637ff <unknown>
#7 0x560fdd4089aa <unknown>
#8 0x560fdd3d6662 <unknown>
#9 0x560fdd3fc660 <unknown>
#10 0x560fdd3d6433 <unknown>
#11 0x560fdd3a2ea3 <unknown>
#12 0x560fdd3a3b01 <unknown>
#13 0x560fdd873b3b <unknown>
#14 0x560fdd877a21 <unknown>
#15 0x560fdd85ac32 <unknown>
#16 0x560fdd878594 <unknown>
#17 0x560fdd83eeef <unknown>
#18 0x560fdd89cd98 <unknown>
#19 0x560fdd89cf76 <unknown>
#20 0x560fdd8adb36 <unknown>
#21 0x7fb22d69caa4 <unknown>
#22 0x7fb22d729c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJQcm9kdWN0IEluZm9ybWF0aW9uIFBhZ2UgLSBvdmVydmlldyAyNTQ2IiwiaXRlbUFjdGlvbiI6IlZpZXcgSXRlbSIsInNvdXJjZSI6eyJwYWdlVHlwZSI6InByb2R1Y3RfaW5mb3JtYXRpb24iLCJsb2NhbGUiOiJpdF9JVCIsImNvbnRlbnRab25lcyI6WyJnbG9iYWxfUElfTkwiLCJwaV9iYW5uZXJfTkwiLCJlcXMtc3BlY2lhbF9OTCJdLCJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9nbGMvb3ZlcnZpZXcuaHRtbCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjMifSwiZmxhZ3MiOnsicGFnZVZpZXciOnRydWV9LCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6Ijk4MzYwMTMwOS4xNzQ1NDM2NzE5In0sImFub25JZCI6Ijk3ZjA2Zjk1MWYzOGY3NWYifSwicGVyZm9ybWFuY2UiOnt9LCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9LCJjYXRhbG9nIjp7IlByb2R1Y3QiOnsiX2lkIjoiMjU0NiIsImRpbWVuc2lvbnMiOnsiQmF1bXVzdGVyU2hvcnQiOlsiMjU0NiJdfX19LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJfdG9vbHNFdmVudExpbmtJZCI6IjU4NzAxOTEzNjc5NzQ0MjMifQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x560fdd8aecea <unknown>
#1 0x560fdd35f5f0 <unknown>
#2 0x560fdd345e86 <unknown>
#3 0x560fdd34479a <unknown>
#4 0x560fdd344eff <unknown>
#5 0x560fdd344e54 <unknown>
#6 0x560fdd3637ff <unknown>
#7 0x560fdd4089aa <unknown>
#8 0x560fdd3d6662 <unknown>
#9 0x560fdd3fc660 <unknown>
#10 0x560fdd3d6433 <unknown>
#11 0x560fdd3a2ea3 <unknown>
#12 0x560fdd3a3b01 <unknown>
#13 0x560fdd873b3b <unknown>
#14 0x560fdd877a21 <unknown>
#15 0x560fdd85ac32 <unknown>
#16 0x560fdd878594 <unknown>
#17 0x560fdd83eeef <unknown>
#18 0x560fdd89cd98 <unknown>
#19 0x560fdd89cf76 <unknown>
#20 0x560fdd8adb36 <unknown>
#21 0x7fb22d69caa4 <unknown>
#22 0x7fb22d729c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gb3ZlcnZpZXciLCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6Ijk4MzYwMTMwOS4xNzQ1NDM2NzE5In0sImFub25JZCI6Ijk3ZjA2Zjk1MWYzOGY3NWYifSwic291cmNlIjp7InVybCI6Imh0dHBzOi8vd3d3Lm1lcmNlZGVzLWJlbnouaXQvcGFzc2VuZ2VyY2Fycy9tb2RlbHMvc3V2L2dsYy9vdmVydmlldy5odG1sIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI2MyIsImNvbnRlbnRab25lcyI6W119LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJfdG9vbHNFdmVudExpbmtJZCI6IjAzNzI2ODcwMTY1NjgyODI3NCIsImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX19: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x560fdd8aecea <unknown>
#1 0x560fdd35f5f0 <unknown>
#2 0x560fdd345e86 <unknown>
#3 0x560fdd34479a <unknown>
#4 0x560fdd344eff <unknown>
#5 0x560fdd344e54 <unknown>
#6 0x560fdd3637ff <unknown>
#7 0x560fdd4089aa <unknown>
#8 0x560fdd3d6662 <unknown>
#9 0x560fdd3fc660 <unknown>
#10 0x560fdd3d6433 <unknown>
#11 0x560fdd3a2ea3 <unknown>
#12 0x560fdd3a3b01 <unknown>
#13 0x560fdd873b3b <unknown>
#14 0x560fdd877a21 <unknown>
#15 0x560fdd85ac32 <unknown>
#16 0x560fdd878594 <unknown>
#17 0x560fdd83eeef <unknown>
#18 0x560fdd89cd98 <unknown>
#19 0x560fdd89cf76 <unknown>
#20 0x560fdd8adb36 <unknown>
#21 0x7fb22d69caa4 <unknown>
#22 0x7fb22d729c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJzZXRfdXNlcl9hdHRyaWJ1dGUiLCJhY2NvdW50Ijp7ImF0dHJpYnV0ZXMiOnsibGFzdFBpUGFnZSI6eyJ2ZWhpY2xlUEkiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9nbGMvb3ZlcnZpZXcuaHRtbCIsInZlaGljbGVDb2RlIjoieDI1NCIsInZlaGljbGVCTSI6IjI1NDYiLCJ2ZWhpY2xlUElIaXN0b3J5IjoiMjU0NiIsInRpbWVzdGFtcCI6MTc0NTQzNjcyMzE2MSwiZXhwaXJhdGlvbiI6MTIwfX19LCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6Ijk4MzYwMTMwOS4xNzQ1NDM2NzE5In0sImFub25JZCI6Ijk3ZjA2Zjk1MWYzOGY3NWYifSwic291cmNlIjp7InVybCI6Imh0dHBzOi8vd3d3Lm1lcmNlZGVzLWJlbnouaXQvcGFzc2VuZ2VyY2Fycy9tb2RlbHMvc3V2L2dsYy9vdmVydmlldy5odG1sIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI2MyIsImNvbnRlbnRab25lcyI6W119LCJjb25zZW50cyI6W10sIl90b29sc0V2ZW50TGlua0lkIjoiNzIwMzUzMjQ4MjA5NTYwOCIsImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX19: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x560fdd8aecea <unknown>
#1 0x560fdd35f5f0 <unknown>
#2 0x560fdd345e86 <unknown>
#3 0x560fdd34479a <unknown>
#4 0x560fdd344eff <unknown>
#5 0x560fdd344e54 <unknown>
#6 0x560fdd3637ff <unknown>
#7 0x560fdd4089aa <unknown>
#8 0x560fdd3d6662 <unknown>
#9 0x560fdd3fc660 <unknown>
#10 0x560fdd3d6433 <unknown>
#11 0x560fdd3a2ea3 <unknown>
#12 0x560fdd3a3b01 <unknown>
#13 0x560fdd873b3b <unknown>
#14 0x560fdd877a21 <unknown>
#15 0x560fdd85ac32 <unknown>
#16 0x560fdd878594 <unknown>
#17 0x560fdd83eeef <unknown>
#18 0x560fdd89cd98 <unknown>
#19 0x560fdd89cf76 <unknown>
#20 0x560fdd8adb36 <unknown>
#21 0x7fb22d69caa4 <unknown>
#22 0x7fb22d729c3c <unknown>

ERROR    root:VerifyPersonalizationAndCapture.py:18 ‚ùå Error attaching screenshot to Allure: [Errno 2] No such file or directory: '/home/runner/work/QA-App-Allure/QA-App-Allure/Tests/BFV1_attempt_1.png'