ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gb3ZlcnZpZXciLCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjE1NTgyMTIxOS4xNzQ1NDgwMzExIn0sImFub25JZCI6IjY5MDYyMmY4Yjg1ZjgwYjQifSwic291cmNlIjp7InVybCI6Imh0dHBzOi8vd3d3Lm1lcmNlZGVzLWJlbnouaXQvcGFzc2VuZ2VyY2Fycy9tb2RlbHMvY2FicmlvbGV0LXJvYWRzdGVyL2NsZS9vdmVydmlldy5odG1sIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI2MyIsImNvbnRlbnRab25lcyI6W119LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJwZXJmb3JtYW5jZSI6eyJzZGtQYXJzZVRpbWUiOjF9LCJfdG9vbHNFdmVudExpbmtJZCI6Ijc3MjY2OTIxNDY4NDI5NjUiLCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9fQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x559390f48cea <unknown>
#1 0x5593909f95f0 <unknown>
#2 0x5593909dfe86 <unknown>
#3 0x5593909de79a <unknown>
#4 0x5593909deeff <unknown>
#5 0x5593909dee54 <unknown>
#6 0x5593909fd7ff <unknown>
#7 0x559390aa29aa <unknown>
#8 0x559390a70662 <unknown>
#9 0x559390a96660 <unknown>
#10 0x559390a70433 <unknown>
#11 0x559390a3cea3 <unknown>
#12 0x559390a3db01 <unknown>
#13 0x559390f0db3b <unknown>
#14 0x559390f11a21 <unknown>
#15 0x559390ef4c32 <unknown>
#16 0x559390f12594 <unknown>
#17 0x559390ed8eef <unknown>
#18 0x559390f36d98 <unknown>
#19 0x559390f36f76 <unknown>
#20 0x559390f47b36 <unknown>
#21 0x7f2bc2a9caa4 <unknown>
#22 0x7f2bc2b29c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJpdGVtQWN0aW9uIjoiVmlldyBJdGVtIiwiY2F0YWxvZyI6eyJJdGVtQ2xhc3MiOnsiX2lkIjoib3ZlcnZpZXcifX0sInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiMTU1ODIxMjE5LjE3NDU0ODAzMTEifSwiYW5vbklkIjoiNjkwNjIyZjhiODVmODBiNCJ9LCJzb3VyY2UiOnsidXJsIjoiaHR0cHM6Ly93d3cubWVyY2VkZXMtYmVuei5pdC9wYXNzZW5nZXJjYXJzL21vZGVscy9jYWJyaW9sZXQtcm9hZHN0ZXIvY2xlL292ZXJ2aWV3Lmh0bWwiLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjYzIiwiY29udGVudFpvbmVzIjpbXX0sImNvbnNlbnRzIjpbXSwiYWNjb3VudCI6e30sIl90b29sc0V2ZW50TGlua0lkIjoiMzgxODM2NTYwMTE3NzEwODMiLCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9fQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x559390f48cea <unknown>
#1 0x5593909f95f0 <unknown>
#2 0x5593909dfe86 <unknown>
#3 0x5593909de79a <unknown>
#4 0x5593909deeff <unknown>
#5 0x5593909dee54 <unknown>
#6 0x5593909fd7ff <unknown>
#7 0x559390aa29aa <unknown>
#8 0x559390a70662 <unknown>
#9 0x559390a96660 <unknown>
#10 0x559390a70433 <unknown>
#11 0x559390a3cea3 <unknown>
#12 0x559390a3db01 <unknown>
#13 0x559390f0db3b <unknown>
#14 0x559390f11a21 <unknown>
#15 0x559390ef4c32 <unknown>
#16 0x559390f12594 <unknown>
#17 0x559390ed8eef <unknown>
#18 0x559390f36d98 <unknown>
#19 0x559390f36f76 <unknown>
#20 0x559390f47b36 <unknown>
#21 0x7f2bc2a9caa4 <unknown>
#22 0x7f2bc2b29c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJQcm9kdWN0IEluZm9ybWF0aW9uIFBhZ2UgLSBvdmVydmlldyAyMzY0IiwiaXRlbUFjdGlvbiI6IlZpZXcgSXRlbSIsInNvdXJjZSI6eyJwYWdlVHlwZSI6InByb2R1Y3RfaW5mb3JtYXRpb24iLCJsb2NhbGUiOiJpdF9JVCIsImNvbnRlbnRab25lcyI6WyJnbG9iYWxfUElfTkwiLCJwaV9iYW5uZXJfTkwiLCJlcXMtc3BlY2lhbF9OTCJdLCJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL2NhYnJpb2xldC1yb2Fkc3Rlci9jbGUvb3ZlcnZpZXcuaHRtbCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjMifSwiZmxhZ3MiOnsicGFnZVZpZXciOnRydWV9LCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjE1NTgyMTIxOS4xNzQ1NDgwMzExIn0sImFub25JZCI6IjY5MDYyMmY4Yjg1ZjgwYjQifSwicGVyZm9ybWFuY2UiOnsic2RrUGFyc2VUaW1lIjoxfSwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfSwiY2F0YWxvZyI6eyJQcm9kdWN0Ijp7Il9pZCI6IjIzNjQiLCJkaW1lbnNpb25zIjp7IkJhdW11c3RlclNob3J0IjpbIjIzNjQiXX19fSwiY29uc2VudHMiOltdLCJhY2NvdW50Ijp7fSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiI1MTQ5NzE0MDc5OTYzMzM4In0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x559390f48cea <unknown>
#1 0x5593909f95f0 <unknown>
#2 0x5593909dfe86 <unknown>
#3 0x5593909de79a <unknown>
#4 0x5593909deeff <unknown>
#5 0x5593909dee54 <unknown>
#6 0x5593909fd7ff <unknown>
#7 0x559390aa29aa <unknown>
#8 0x559390a70662 <unknown>
#9 0x559390a96660 <unknown>
#10 0x559390a70433 <unknown>
#11 0x559390a3cea3 <unknown>
#12 0x559390a3db01 <unknown>
#13 0x559390f0db3b <unknown>
#14 0x559390f11a21 <unknown>
#15 0x559390ef4c32 <unknown>
#16 0x559390f12594 <unknown>
#17 0x559390ed8eef <unknown>
#18 0x559390f36d98 <unknown>
#19 0x559390f36f76 <unknown>
#20 0x559390f47b36 <unknown>
#21 0x7f2bc2a9caa4 <unknown>
#22 0x7f2bc2b29c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJzZXRfdXNlcl9hdHRyaWJ1dGUiLCJhY2NvdW50Ijp7ImF0dHJpYnV0ZXMiOnsibGFzdFBpUGFnZSI6eyJ2ZWhpY2xlUEkiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL2NhYnJpb2xldC1yb2Fkc3Rlci9jbGUvb3ZlcnZpZXcuaHRtbCIsInZlaGljbGVDb2RlIjoiYTIzNiIsInZlaGljbGVCTSI6IjIzNjQiLCJ2ZWhpY2xlUElIaXN0b3J5IjoiMjM2NCIsInRpbWVzdGFtcCI6MTc0NTQ4MDMxNTU2NywiZXhwaXJhdGlvbiI6MTIwfX19LCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjE1NTgyMTIxOS4xNzQ1NDgwMzExIn0sImFub25JZCI6IjY5MDYyMmY4Yjg1ZjgwYjQifSwic291cmNlIjp7InVybCI6Imh0dHBzOi8vd3d3Lm1lcmNlZGVzLWJlbnouaXQvcGFzc2VuZ2VyY2Fycy9tb2RlbHMvY2FicmlvbGV0LXJvYWRzdGVyL2NsZS9vdmVydmlldy5odG1sIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI2MyIsImNvbnRlbnRab25lcyI6W119LCJjb25zZW50cyI6W10sIl90b29sc0V2ZW50TGlua0lkIjoiOTcxMjczODcxNjE3MTU0MyIsImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX19: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x559390f48cea <unknown>
#1 0x5593909f95f0 <unknown>
#2 0x5593909dfe86 <unknown>
#3 0x5593909de79a <unknown>
#4 0x5593909deeff <unknown>
#5 0x5593909dee54 <unknown>
#6 0x5593909fd7ff <unknown>
#7 0x559390aa29aa <unknown>
#8 0x559390a70662 <unknown>
#9 0x559390a96660 <unknown>
#10 0x559390a70433 <unknown>
#11 0x559390a3cea3 <unknown>
#12 0x559390a3db01 <unknown>
#13 0x559390f0db3b <unknown>
#14 0x559390f11a21 <unknown>
#15 0x559390ef4c32 <unknown>
#16 0x559390f12594 <unknown>
#17 0x559390ed8eef <unknown>
#18 0x559390f36d98 <unknown>
#19 0x559390f36f76 <unknown>
#20 0x559390f47b36 <unknown>
#21 0x7f2bc2a9caa4 <unknown>
#22 0x7f2bc2b29c3c <unknown>

ERROR    root:VerifyPersonalizationAndCapture.py:18 ‚ùå Error attaching screenshot to Allure: [Errno 2] No such file or directory: '/home/runner/work/QA-App-Allure/QA-App-Allure/Tests/BFV1_attempt_1.png'