ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJQcm9kdWN0IEluZm9ybWF0aW9uIFBhZ2UgLSBvdmVydmlldyAyNTQzIiwidXNlciI6eyJhdHRyaWJ1dGVzIjp7ImdhQ2xpZW50SUQiOiIyMDU1MTI2ODExLjE3NDU0NDA2NTIifSwiYW5vbklkIjoiOTgzNDI3NjNlZGQyYjBjNyJ9LCJzb3VyY2UiOnsidXJsIjoiaHR0cHM6Ly93d3cubWVyY2VkZXMtYmVuei5pdC9wYXNzZW5nZXJjYXJzL21vZGVscy9zdXYvZ2xjLWNvdXBlL292ZXJ2aWV3Lmh0bWwiLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjYzIiwiY29udGVudFpvbmVzIjpbXX0sImNvbnNlbnRzIjpbXSwiYWNjb3VudCI6e30sIl90b29sc0V2ZW50TGlua0lkIjoiNTcyMzI1NDExNjI4NzExOCIsImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX19: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x55abb8183cea <unknown>
#1 0x55abb7c345f0 <unknown>
#2 0x55abb7c1ae86 <unknown>
#3 0x55abb7c1979a <unknown>
#4 0x55abb7c19eff <unknown>
#5 0x55abb7c19e54 <unknown>
#6 0x55abb7c387ff <unknown>
#7 0x55abb7cdd9aa <unknown>
#8 0x55abb7cab662 <unknown>
#9 0x55abb7cd1660 <unknown>
#10 0x55abb7cab433 <unknown>
#11 0x55abb7c77ea3 <unknown>
#12 0x55abb7c78b01 <unknown>
#13 0x55abb8148b3b <unknown>
#14 0x55abb814ca21 <unknown>
#15 0x55abb812fc32 <unknown>
#16 0x55abb814d594 <unknown>
#17 0x55abb8113eef <unknown>
#18 0x55abb8171d98 <unknown>
#19 0x55abb8171f76 <unknown>
#20 0x55abb8182b36 <unknown>
#21 0x7f5ff4a9caa4 <unknown>
#22 0x7f5ff4b29c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJpdGVtQWN0aW9uIjoiVmlldyBJdGVtIiwiY2F0YWxvZyI6eyJJdGVtQ2xhc3MiOnsiX2lkIjoiaGlnaGxpZ2h0cyJ9fSwidXNlciI6eyJhdHRyaWJ1dGVzIjp7ImdhQ2xpZW50SUQiOiIyMDU1MTI2ODExLjE3NDU0NDA2NTIifSwiYW5vbklkIjoiOTgzNDI3NjNlZGQyYjBjNyJ9LCJzb3VyY2UiOnsidXJsIjoiaHR0cHM6Ly93d3cubWVyY2VkZXMtYmVuei5pdC9wYXNzZW5nZXJjYXJzL21vZGVscy9zdXYvZ2xjLWNvdXBlL292ZXJ2aWV3Lmh0bWwiLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjYzIiwiY29udGVudFpvbmVzIjpbXX0sImNvbnNlbnRzIjpbXSwiYWNjb3VudCI6e30sIl90b29sc0V2ZW50TGlua0lkIjoiNTYxMDYzNzYwNTEyMjk1NSIsImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX19: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x55abb8183cea <unknown>
#1 0x55abb7c345f0 <unknown>
#2 0x55abb7c1ae86 <unknown>
#3 0x55abb7c1979a <unknown>
#4 0x55abb7c19eff <unknown>
#5 0x55abb7c19e54 <unknown>
#6 0x55abb7c387ff <unknown>
#7 0x55abb7cdd9aa <unknown>
#8 0x55abb7cab662 <unknown>
#9 0x55abb7cd1660 <unknown>
#10 0x55abb7cab433 <unknown>
#11 0x55abb7c77ea3 <unknown>
#12 0x55abb7c78b01 <unknown>
#13 0x55abb8148b3b <unknown>
#14 0x55abb814ca21 <unknown>
#15 0x55abb812fc32 <unknown>
#16 0x55abb814d594 <unknown>
#17 0x55abb8113eef <unknown>
#18 0x55abb8171d98 <unknown>
#19 0x55abb8171f76 <unknown>
#20 0x55abb8182b36 <unknown>
#21 0x7f5ff4a9caa4 <unknown>
#22 0x7f5ff4b29c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJQcm9kdWN0IEluZm9ybWF0aW9uIFBhZ2UgLSBoaWdobGlnaHRzIDI1NDMiLCJpdGVtQWN0aW9uIjoiVmlldyBJdGVtIiwic291cmNlIjp7InBhZ2VUeXBlIjoicHJvZHVjdF9pbmZvcm1hdGlvbiIsImxvY2FsZSI6Iml0X0lUIiwiY29udGVudFpvbmVzIjpbImdsb2JhbF9QSV9OTCIsInBpX2Jhbm5lcl9OTCIsImVxcy1zcGVjaWFsX05MIl0sInVybCI6Imh0dHBzOi8vd3d3Lm1lcmNlZGVzLWJlbnouaXQvcGFzc2VuZ2VyY2Fycy9tb2RlbHMvc3V2L2dsYy1jb3VwZS9vdmVydmlldy5odG1sIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI2MyJ9LCJmbGFncyI6eyJwYWdlVmlldyI6dHJ1ZX0sInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiMjA1NTEyNjgxMS4xNzQ1NDQwNjUyIn0sImFub25JZCI6Ijk4MzQyNzYzZWRkMmIwYzcifSwicGVyZm9ybWFuY2UiOnt9LCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9LCJjYXRhbG9nIjp7IlByb2R1Y3QiOnsiX2lkIjoiMjU0MyIsImRpbWVuc2lvbnMiOnsiQmF1bXVzdGVyU2hvcnQiOlsiMjU0MyJdfX19LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJfdG9vbHNFdmVudExpbmtJZCI6IjE0MDk0NjUzNDA5Njk0MTU4In0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x55abb8183cea <unknown>
#1 0x55abb7c345f0 <unknown>
#2 0x55abb7c1ae86 <unknown>
#3 0x55abb7c1979a <unknown>
#4 0x55abb7c19eff <unknown>
#5 0x55abb7c19e54 <unknown>
#6 0x55abb7c387ff <unknown>
#7 0x55abb7cdd9aa <unknown>
#8 0x55abb7cab662 <unknown>
#9 0x55abb7cd1660 <unknown>
#10 0x55abb7cab433 <unknown>
#11 0x55abb7c77ea3 <unknown>
#12 0x55abb7c78b01 <unknown>
#13 0x55abb8148b3b <unknown>
#14 0x55abb814ca21 <unknown>
#15 0x55abb812fc32 <unknown>
#16 0x55abb814d594 <unknown>
#17 0x55abb8113eef <unknown>
#18 0x55abb8171d98 <unknown>
#19 0x55abb8171f76 <unknown>
#20 0x55abb8182b36 <unknown>
#21 0x7f5ff4a9caa4 <unknown>
#22 0x7f5ff4b29c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gb3ZlcnZpZXciLCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjIwNTUxMjY4MTEuMTc0NTQ0MDY1MiJ9LCJhbm9uSWQiOiI5ODM0Mjc2M2VkZDJiMGM3In0sInNvdXJjZSI6eyJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9nbGMtY291cGUvb3ZlcnZpZXcuaHRtbCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjMiLCJjb250ZW50Wm9uZXMiOltdfSwiY29uc2VudHMiOltdLCJhY2NvdW50Ijp7fSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiI0MzI2NTY5NDEyNDQ2MzUzIiwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfX0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x55abb8183cea <unknown>
#1 0x55abb7c345f0 <unknown>
#2 0x55abb7c1ae86 <unknown>
#3 0x55abb7c1979a <unknown>
#4 0x55abb7c19eff <unknown>
#5 0x55abb7c19e54 <unknown>
#6 0x55abb7c387ff <unknown>
#7 0x55abb7cdd9aa <unknown>
#8 0x55abb7cab662 <unknown>
#9 0x55abb7cd1660 <unknown>
#10 0x55abb7cab433 <unknown>
#11 0x55abb7c77ea3 <unknown>
#12 0x55abb7c78b01 <unknown>
#13 0x55abb8148b3b <unknown>
#14 0x55abb814ca21 <unknown>
#15 0x55abb812fc32 <unknown>
#16 0x55abb814d594 <unknown>
#17 0x55abb8113eef <unknown>
#18 0x55abb8171d98 <unknown>
#19 0x55abb8171f76 <unknown>
#20 0x55abb8182b36 <unknown>
#21 0x7f5ff4a9caa4 <unknown>
#22 0x7f5ff4b29c3c <unknown>

ERROR    root:VerifyPersonalizationAndCapture.py:18 ‚ùå Error attaching screenshot to Allure: [Errno 2] No such file or directory: '/home/runner/work/QA-App-Allure/QA-App-Allure/Tests/BFV1_attempt_1.png'