ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJQcm9kdWN0IEluZm9ybWF0aW9uIFBhZ2UgLSBvdmVydmlldyAyNDc3IiwiaXRlbUFjdGlvbiI6IlZpZXcgSXRlbSIsInNvdXJjZSI6eyJwYWdlVHlwZSI6InByb2R1Y3RfaW5mb3JtYXRpb24iLCJsb2NhbGUiOiJpdF9JVCIsImNvbnRlbnRab25lcyI6WyJnbG9iYWxfUElfTkwiLCJwaV9iYW5uZXJfTkwiLCJlcXMtc3BlY2lhbF9OTCJdLCJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9nbGEvb3ZlcnZpZXcuaHRtbCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjMifSwiZmxhZ3MiOnsicGFnZVZpZXciOnRydWV9LCJ1c2VyIjp7ImFub25JZCI6IjkzZDg1MTJmZWM4MzdhY2UifSwicGVyZm9ybWFuY2UiOnsic2RrUGFyc2VUaW1lIjoxfSwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfSwiY2F0YWxvZyI6eyJQcm9kdWN0Ijp7Il9pZCI6IjI0NzciLCJkaW1lbnNpb25zIjp7IkJhdW11c3RlclNob3J0IjpbIjI0NzciXX19fSwiY29uc2VudHMiOltdLCJhY2NvdW50Ijp7fSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiI0MzY2NDI4MDgwMzcyNjY5NiJ9: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x556259089cea <unknown>
#1 0x556258b3a5f0 <unknown>
#2 0x556258b20e86 <unknown>
#3 0x556258b1f79a <unknown>
#4 0x556258b1feff <unknown>
#5 0x556258b1fe54 <unknown>
#6 0x556258b3e7ff <unknown>
#7 0x556258be39aa <unknown>
#8 0x556258bb1662 <unknown>
#9 0x556258bd7660 <unknown>
#10 0x556258bb1433 <unknown>
#11 0x556258b7dea3 <unknown>
#12 0x556258b7eb01 <unknown>
#13 0x55625904eb3b <unknown>
#14 0x556259052a21 <unknown>
#15 0x556259035c32 <unknown>
#16 0x556259053594 <unknown>
#17 0x556259019eef <unknown>
#18 0x556259077d98 <unknown>
#19 0x556259077f76 <unknown>
#20 0x556259088b36 <unknown>
#21 0x7f3087a9caa4 <unknown>
#22 0x7f3087b29c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJpdGVtQWN0aW9uIjoiVmlldyBJdGVtIiwiY2F0YWxvZyI6eyJJdGVtQ2xhc3MiOnsiX2lkIjoib3ZlcnZpZXcifX0sInNvdXJjZSI6eyJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9nbGEvb3ZlcnZpZXcuaHRtbCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjMiLCJjb250ZW50Wm9uZXMiOltdfSwidXNlciI6eyJhbm9uSWQiOiI5M2Q4NTEyZmVjODM3YWNlIn0sImNvbnNlbnRzIjpbXSwiYWNjb3VudCI6e30sIl90b29sc0V2ZW50TGlua0lkIjoiMTk4Mzg4NTg3ODIxMzIxNzQiLCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9fQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x556259089cea <unknown>
#1 0x556258b3a5f0 <unknown>
#2 0x556258b20e86 <unknown>
#3 0x556258b1f79a <unknown>
#4 0x556258b1feff <unknown>
#5 0x556258b1fe54 <unknown>
#6 0x556258b3e7ff <unknown>
#7 0x556258be39aa <unknown>
#8 0x556258bb1662 <unknown>
#9 0x556258bd7660 <unknown>
#10 0x556258bb1433 <unknown>
#11 0x556258b7dea3 <unknown>
#12 0x556258b7eb01 <unknown>
#13 0x55625904eb3b <unknown>
#14 0x556259052a21 <unknown>
#15 0x556259035c32 <unknown>
#16 0x556259053594 <unknown>
#17 0x556259019eef <unknown>
#18 0x556259077d98 <unknown>
#19 0x556259077f76 <unknown>
#20 0x556259088b36 <unknown>
#21 0x7f3087a9caa4 <unknown>
#22 0x7f3087b29c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gb3ZlcnZpZXciLCJzb3VyY2UiOnsidXJsIjoiaHR0cHM6Ly93d3cubWVyY2VkZXMtYmVuei5pdC9wYXNzZW5nZXJjYXJzL21vZGVscy9zdXYvZ2xhL292ZXJ2aWV3Lmh0bWwiLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjYzIiwiY29udGVudFpvbmVzIjpbXX0sInVzZXIiOnsiYW5vbklkIjoiOTNkODUxMmZlYzgzN2FjZSJ9LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJwZXJmb3JtYW5jZSI6eyJzZGtQYXJzZVRpbWUiOjF9LCJfdG9vbHNFdmVudExpbmtJZCI6Ijg1MTEzNTA2MjE1MTgwNiIsImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX19: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x556259089cea <unknown>
#1 0x556258b3a5f0 <unknown>
#2 0x556258b20e86 <unknown>
#3 0x556258b1f79a <unknown>
#4 0x556258b1feff <unknown>
#5 0x556258b1fe54 <unknown>
#6 0x556258b3e7ff <unknown>
#7 0x556258be39aa <unknown>
#8 0x556258bb1662 <unknown>
#9 0x556258bd7660 <unknown>
#10 0x556258bb1433 <unknown>
#11 0x556258b7dea3 <unknown>
#12 0x556258b7eb01 <unknown>
#13 0x55625904eb3b <unknown>
#14 0x556259052a21 <unknown>
#15 0x556259035c32 <unknown>
#16 0x556259053594 <unknown>
#17 0x556259019eef <unknown>
#18 0x556259077d98 <unknown>
#19 0x556259077f76 <unknown>
#20 0x556259088b36 <unknown>
#21 0x7f3087a9caa4 <unknown>
#22 0x7f3087b29c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJzZXRfdXNlcl9hdHRyaWJ1dGUiLCJhY2NvdW50Ijp7ImF0dHJpYnV0ZXMiOnsibGFzdFBpUGFnZSI6eyJ2ZWhpY2xlUEkiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9nbGEvb3ZlcnZpZXcuaHRtbCIsInZlaGljbGVDb2RlIjoiaDI0Ny1mbCIsInZlaGljbGVCTSI6IjI0NzciLCJ2ZWhpY2xlUElIaXN0b3J5IjoiMjQ3NyIsInRpbWVzdGFtcCI6MTc0NTQ0MTA0MzcxOCwiZXhwaXJhdGlvbiI6MTIwfX19LCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjEwMjYxMDM3NDMuMTc0NTQ0MTA0MiJ9LCJhbm9uSWQiOiI5M2Q4NTEyZmVjODM3YWNlIn0sInNvdXJjZSI6eyJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9nbGEvb3ZlcnZpZXcuaHRtbCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjMiLCJjb250ZW50Wm9uZXMiOltdfSwiY29uc2VudHMiOltdLCJfdG9vbHNFdmVudExpbmtJZCI6IjA1NDM2NDM0OTUwNzM3NjkiLCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9fQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x556259089cea <unknown>
#1 0x556258b3a5f0 <unknown>
#2 0x556258b20e86 <unknown>
#3 0x556258b1f79a <unknown>
#4 0x556258b1feff <unknown>
#5 0x556258b1fe54 <unknown>
#6 0x556258b3e7ff <unknown>
#7 0x556258be39aa <unknown>
#8 0x556258bb1662 <unknown>
#9 0x556258bd7660 <unknown>
#10 0x556258bb1433 <unknown>
#11 0x556258b7dea3 <unknown>
#12 0x556258b7eb01 <unknown>
#13 0x55625904eb3b <unknown>
#14 0x556259052a21 <unknown>
#15 0x556259035c32 <unknown>
#16 0x556259053594 <unknown>
#17 0x556259019eef <unknown>
#18 0x556259077d98 <unknown>
#19 0x556259077f76 <unknown>
#20 0x556259088b36 <unknown>
#21 0x7f3087a9caa4 <unknown>
#22 0x7f3087b29c3c <unknown>

ERROR    root:VerifyPersonalizationAndCapture.py:111 ❌ Image not found in the specified selector. Error: Message: 

ERROR    root:VerifyPersonalizationAndCapture.py:18 ❌ Error attaching screenshot to Allure: [Errno 2] No such file or directory: '/home/runner/work/QA-App-Allure/QA-App-Allure/Tests/BFV1_attempt_1.png'
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6252448bd0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/185733702300fdb3e21d775bb94fff8a
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f625244acd0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/185733702300fdb3e21d775bb94fff8a
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f625244b790>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/185733702300fdb3e21d775bb94fff8a
ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gb3ZlcnZpZXciLCJzb3VyY2UiOnsidXJsIjoiaHR0cHM6Ly93d3cubWVyY2VkZXMtYmVuei5pdC9wYXNzZW5nZXJjYXJzL21vZGVscy9zdXYvZ2xhL292ZXJ2aWV3Lmh0bWwiLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjYzIiwiY29udGVudFpvbmVzIjpbXX0sInVzZXIiOnsiYW5vbklkIjoiMmM3ODdiYzBmMjIxYmI3NCJ9LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJfdG9vbHNFdmVudExpbmtJZCI6IjQzNDA0OTM0MzA4MzAxMTEzIiwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfX0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x5613cd937cea <unknown>
#1 0x5613cd3e85f0 <unknown>
#2 0x5613cd3cee86 <unknown>
#3 0x5613cd3cd79a <unknown>
#4 0x5613cd3cdeff <unknown>
#5 0x5613cd3cde54 <unknown>
#6 0x5613cd3ec7ff <unknown>
#7 0x5613cd4919aa <unknown>
#8 0x5613cd45f662 <unknown>
#9 0x5613cd485660 <unknown>
#10 0x5613cd45f433 <unknown>
#11 0x5613cd42bea3 <unknown>
#12 0x5613cd42cb01 <unknown>
#13 0x5613cd8fcb3b <unknown>
#14 0x5613cd900a21 <unknown>
#15 0x5613cd8e3c32 <unknown>
#16 0x5613cd901594 <unknown>
#17 0x5613cd8c7eef <unknown>
#18 0x5613cd925d98 <unknown>
#19 0x5613cd925f76 <unknown>
#20 0x5613cd936b36 <unknown>
#21 0x7fc52649caa4 <unknown>
#22 0x7fc526529c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJpdGVtQWN0aW9uIjoiVmlldyBJdGVtIiwiY2F0YWxvZyI6eyJJdGVtQ2xhc3MiOnsiX2lkIjoib3ZlcnZpZXcifX0sInNvdXJjZSI6eyJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9nbGEvb3ZlcnZpZXcuaHRtbCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjMiLCJjb250ZW50Wm9uZXMiOltdfSwidXNlciI6eyJhbm9uSWQiOiIyYzc4N2JjMGYyMjFiYjc0In0sImNvbnNlbnRzIjpbXSwiYWNjb3VudCI6e30sIl90b29sc0V2ZW50TGlua0lkIjoiMDEwMDU5MDQzNjY2NzQ5MDM1IiwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfX0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x5613cd937cea <unknown>
#1 0x5613cd3e85f0 <unknown>
#2 0x5613cd3cee86 <unknown>
#3 0x5613cd3cd79a <unknown>
#4 0x5613cd3cdeff <unknown>
#5 0x5613cd3cde54 <unknown>
#6 0x5613cd3ec7ff <unknown>
#7 0x5613cd4919aa <unknown>
#8 0x5613cd45f662 <unknown>
#9 0x5613cd485660 <unknown>
#10 0x5613cd45f433 <unknown>
#11 0x5613cd42bea3 <unknown>
#12 0x5613cd42cb01 <unknown>
#13 0x5613cd8fcb3b <unknown>
#14 0x5613cd900a21 <unknown>
#15 0x5613cd8e3c32 <unknown>
#16 0x5613cd901594 <unknown>
#17 0x5613cd8c7eef <unknown>
#18 0x5613cd925d98 <unknown>
#19 0x5613cd925f76 <unknown>
#20 0x5613cd936b36 <unknown>
#21 0x7fc52649caa4 <unknown>
#22 0x7fc526529c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJQcm9kdWN0IEluZm9ybWF0aW9uIFBhZ2UgLSBvdmVydmlldyAyNDc3IiwiaXRlbUFjdGlvbiI6IlZpZXcgSXRlbSIsInNvdXJjZSI6eyJwYWdlVHlwZSI6InByb2R1Y3RfaW5mb3JtYXRpb24iLCJsb2NhbGUiOiJpdF9JVCIsImNvbnRlbnRab25lcyI6WyJnbG9iYWxfUElfTkwiLCJwaV9iYW5uZXJfTkwiLCJlcXMtc3BlY2lhbF9OTCJdLCJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9nbGEvb3ZlcnZpZXcuaHRtbCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjMifSwiZmxhZ3MiOnsicGFnZVZpZXciOnRydWV9LCJ1c2VyIjp7ImFub25JZCI6IjJjNzg3YmMwZjIyMWJiNzQifSwicGVyZm9ybWFuY2UiOnt9LCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9LCJjYXRhbG9nIjp7IlByb2R1Y3QiOnsiX2lkIjoiMjQ3NyIsImRpbWVuc2lvbnMiOnsiQmF1bXVzdGVyU2hvcnQiOlsiMjQ3NyJdfX19LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJfdG9vbHNFdmVudExpbmtJZCI6IjQ3ODkwNjUyMzAxMzAwNzQifQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x5613cd937cea <unknown>
#1 0x5613cd3e85f0 <unknown>
#2 0x5613cd3cee86 <unknown>
#3 0x5613cd3cd79a <unknown>
#4 0x5613cd3cdeff <unknown>
#5 0x5613cd3cde54 <unknown>
#6 0x5613cd3ec7ff <unknown>
#7 0x5613cd4919aa <unknown>
#8 0x5613cd45f662 <unknown>
#9 0x5613cd485660 <unknown>
#10 0x5613cd45f433 <unknown>
#11 0x5613cd42bea3 <unknown>
#12 0x5613cd42cb01 <unknown>
#13 0x5613cd8fcb3b <unknown>
#14 0x5613cd900a21 <unknown>
#15 0x5613cd8e3c32 <unknown>
#16 0x5613cd901594 <unknown>
#17 0x5613cd8c7eef <unknown>
#18 0x5613cd925d98 <unknown>
#19 0x5613cd925f76 <unknown>
#20 0x5613cd936b36 <unknown>
#21 0x7fc52649caa4 <unknown>
#22 0x7fc526529c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJzZXRfdXNlcl9hdHRyaWJ1dGUiLCJhY2NvdW50Ijp7ImF0dHJpYnV0ZXMiOnsibGFzdFBpUGFnZSI6eyJ2ZWhpY2xlUEkiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9nbGEvb3ZlcnZpZXcuaHRtbCIsInZlaGljbGVDb2RlIjoiaDI0Ny1mbCIsInZlaGljbGVCTSI6IjI0NzciLCJ2ZWhpY2xlUElIaXN0b3J5IjoiMjQ3NyIsInRpbWVzdGFtcCI6MTc0NTQ0MTA3NjA3OCwiZXhwaXJhdGlvbiI6MTIwfX19LCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjEzNzMxNzQzODQuMTc0NTQ0MTA3NCJ9LCJhbm9uSWQiOiIyYzc4N2JjMGYyMjFiYjc0In0sInNvdXJjZSI6eyJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9nbGEvb3ZlcnZpZXcuaHRtbCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjMiLCJjb250ZW50Wm9uZXMiOltdfSwiY29uc2VudHMiOltdLCJfdG9vbHNFdmVudExpbmtJZCI6IjM3MzM0MDA1MzM3MzgxMzI2IiwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfX0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x5613cd937cea <unknown>
#1 0x5613cd3e85f0 <unknown>
#2 0x5613cd3cee86 <unknown>
#3 0x5613cd3cd79a <unknown>
#4 0x5613cd3cdeff <unknown>
#5 0x5613cd3cde54 <unknown>
#6 0x5613cd3ec7ff <unknown>
#7 0x5613cd4919aa <unknown>
#8 0x5613cd45f662 <unknown>
#9 0x5613cd485660 <unknown>
#10 0x5613cd45f433 <unknown>
#11 0x5613cd42bea3 <unknown>
#12 0x5613cd42cb01 <unknown>
#13 0x5613cd8fcb3b <unknown>
#14 0x5613cd900a21 <unknown>
#15 0x5613cd8e3c32 <unknown>
#16 0x5613cd901594 <unknown>
#17 0x5613cd8c7eef <unknown>
#18 0x5613cd925d98 <unknown>
#19 0x5613cd925f76 <unknown>
#20 0x5613cd936b36 <unknown>
#21 0x7fc52649caa4 <unknown>
#22 0x7fc526529c3c <unknown>

ERROR    root:VerifyPersonalizationAndCapture.py:18 ❌ Error attaching screenshot to Allure: [Errno 2] No such file or directory: '/home/runner/work/QA-App-Allure/QA-App-Allure/Tests/BFV1_attempt_2.png'
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6251c22ad0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/185733702300fdb3e21d775bb94fff8a
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6251c231d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/185733702300fdb3e21d775bb94fff8a
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6251c21bd0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/185733702300fdb3e21d775bb94fff8a