ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJpdGVtQWN0aW9uIjoiVmlldyBJdGVtIiwiY2F0YWxvZyI6eyJJdGVtQ2xhc3MiOnsiX2lkIjoib3ZlcnZpZXcifX0sInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiOTEyNDcyMTk5LjE3NDU0Mzk2ODgifSwiYW5vbklkIjoiOTYyNzc2MjVkYzY2ZDA2YiJ9LCJzb3VyY2UiOnsidXJsIjoiaHR0cHM6Ly93d3cubWVyY2VkZXMtYmVuei5pdC9wYXNzZW5nZXJjYXJzL21vZGVscy9zdXYvZ2xjL292ZXJ2aWV3Lmh0bWwiLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjYzIiwiY29udGVudFpvbmVzIjpbXX0sImNvbnNlbnRzIjpbXSwiYWNjb3VudCI6e30sIl90b29sc0V2ZW50TGlua0lkIjoiMzI3ODYwNDY5OTc3MTM3MTQiLCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9fQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x55fac805acea <unknown>
#1 0x55fac7b0b5f0 <unknown>
#2 0x55fac7af1e86 <unknown>
#3 0x55fac7af079a <unknown>
#4 0x55fac7af0eff <unknown>
#5 0x55fac7af0e54 <unknown>
#6 0x55fac7b0f7ff <unknown>
#7 0x55fac7bb49aa <unknown>
#8 0x55fac7b82662 <unknown>
#9 0x55fac7ba8660 <unknown>
#10 0x55fac7b82433 <unknown>
#11 0x55fac7b4eea3 <unknown>
#12 0x55fac7b4fb01 <unknown>
#13 0x55fac801fb3b <unknown>
#14 0x55fac8023a21 <unknown>
#15 0x55fac8006c32 <unknown>
#16 0x55fac8024594 <unknown>
#17 0x55fac7feaeef <unknown>
#18 0x55fac8048d98 <unknown>
#19 0x55fac8048f76 <unknown>
#20 0x55fac8059b36 <unknown>
#21 0x7fb668e9caa4 <unknown>
#22 0x7fb668f29c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJQcm9kdWN0IEluZm9ybWF0aW9uIFBhZ2UgLSBvdmVydmlldyAyNTQ2IiwiaXRlbUFjdGlvbiI6IlZpZXcgSXRlbSIsInNvdXJjZSI6eyJwYWdlVHlwZSI6InByb2R1Y3RfaW5mb3JtYXRpb24iLCJsb2NhbGUiOiJpdF9JVCIsImNvbnRlbnRab25lcyI6WyJnbG9iYWxfUElfTkwiLCJwaV9iYW5uZXJfTkwiLCJlcXMtc3BlY2lhbF9OTCJdLCJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9nbGMvb3ZlcnZpZXcuaHRtbCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjMifSwiZmxhZ3MiOnsicGFnZVZpZXciOnRydWV9LCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjkxMjQ3MjE5OS4xNzQ1NDM5Njg4In0sImFub25JZCI6Ijk2Mjc3NjI1ZGM2NmQwNmIifSwicGVyZm9ybWFuY2UiOnt9LCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9LCJjYXRhbG9nIjp7IlByb2R1Y3QiOnsiX2lkIjoiMjU0NiIsImRpbWVuc2lvbnMiOnsiQmF1bXVzdGVyU2hvcnQiOlsiMjU0NiJdfX19LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJfdG9vbHNFdmVudExpbmtJZCI6IjI5MjE1MTgxMDQ2ODMwMTUifQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x55fac805acea <unknown>
#1 0x55fac7b0b5f0 <unknown>
#2 0x55fac7af1e86 <unknown>
#3 0x55fac7af079a <unknown>
#4 0x55fac7af0eff <unknown>
#5 0x55fac7af0e54 <unknown>
#6 0x55fac7b0f7ff <unknown>
#7 0x55fac7bb49aa <unknown>
#8 0x55fac7b82662 <unknown>
#9 0x55fac7ba8660 <unknown>
#10 0x55fac7b82433 <unknown>
#11 0x55fac7b4eea3 <unknown>
#12 0x55fac7b4fb01 <unknown>
#13 0x55fac801fb3b <unknown>
#14 0x55fac8023a21 <unknown>
#15 0x55fac8006c32 <unknown>
#16 0x55fac8024594 <unknown>
#17 0x55fac7feaeef <unknown>
#18 0x55fac8048d98 <unknown>
#19 0x55fac8048f76 <unknown>
#20 0x55fac8059b36 <unknown>
#21 0x7fb668e9caa4 <unknown>
#22 0x7fb668f29c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gb3ZlcnZpZXciLCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjkxMjQ3MjE5OS4xNzQ1NDM5Njg4In0sImFub25JZCI6Ijk2Mjc3NjI1ZGM2NmQwNmIifSwic291cmNlIjp7InVybCI6Imh0dHBzOi8vd3d3Lm1lcmNlZGVzLWJlbnouaXQvcGFzc2VuZ2VyY2Fycy9tb2RlbHMvc3V2L2dsYy9vdmVydmlldy5odG1sIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI2MyIsImNvbnRlbnRab25lcyI6W119LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJfdG9vbHNFdmVudExpbmtJZCI6IjE3ODk4NDA3MDY0Mjc3Njc3IiwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfX0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x55fac805acea <unknown>
#1 0x55fac7b0b5f0 <unknown>
#2 0x55fac7af1e86 <unknown>
#3 0x55fac7af079a <unknown>
#4 0x55fac7af0eff <unknown>
#5 0x55fac7af0e54 <unknown>
#6 0x55fac7b0f7ff <unknown>
#7 0x55fac7bb49aa <unknown>
#8 0x55fac7b82662 <unknown>
#9 0x55fac7ba8660 <unknown>
#10 0x55fac7b82433 <unknown>
#11 0x55fac7b4eea3 <unknown>
#12 0x55fac7b4fb01 <unknown>
#13 0x55fac801fb3b <unknown>
#14 0x55fac8023a21 <unknown>
#15 0x55fac8006c32 <unknown>
#16 0x55fac8024594 <unknown>
#17 0x55fac7feaeef <unknown>
#18 0x55fac8048d98 <unknown>
#19 0x55fac8048f76 <unknown>
#20 0x55fac8059b36 <unknown>
#21 0x7fb668e9caa4 <unknown>
#22 0x7fb668f29c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJzZXRfdXNlcl9hdHRyaWJ1dGUiLCJhY2NvdW50Ijp7ImF0dHJpYnV0ZXMiOnsibGFzdFBpUGFnZSI6eyJ2ZWhpY2xlUEkiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9nbGMvb3ZlcnZpZXcuaHRtbCIsInZlaGljbGVDb2RlIjoieDI1NCIsInZlaGljbGVCTSI6IjI1NDYiLCJ2ZWhpY2xlUElIaXN0b3J5IjoiMjU0NiIsInRpbWVzdGFtcCI6MTc0NTQzOTY5MTc3MywiZXhwaXJhdGlvbiI6MTIwfX19LCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjkxMjQ3MjE5OS4xNzQ1NDM5Njg4In0sImFub25JZCI6Ijk2Mjc3NjI1ZGM2NmQwNmIifSwic291cmNlIjp7InVybCI6Imh0dHBzOi8vd3d3Lm1lcmNlZGVzLWJlbnouaXQvcGFzc2VuZ2VyY2Fycy9tb2RlbHMvc3V2L2dsYy9vdmVydmlldy5odG1sIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI2MyIsImNvbnRlbnRab25lcyI6W119LCJjb25zZW50cyI6W10sIl90b29sc0V2ZW50TGlua0lkIjoiOTk3NDUwNjc5NjY3ODkyIiwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfX0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x55fac805acea <unknown>
#1 0x55fac7b0b5f0 <unknown>
#2 0x55fac7af1e86 <unknown>
#3 0x55fac7af079a <unknown>
#4 0x55fac7af0eff <unknown>
#5 0x55fac7af0e54 <unknown>
#6 0x55fac7b0f7ff <unknown>
#7 0x55fac7bb49aa <unknown>
#8 0x55fac7b82662 <unknown>
#9 0x55fac7ba8660 <unknown>
#10 0x55fac7b82433 <unknown>
#11 0x55fac7b4eea3 <unknown>
#12 0x55fac7b4fb01 <unknown>
#13 0x55fac801fb3b <unknown>
#14 0x55fac8023a21 <unknown>
#15 0x55fac8006c32 <unknown>
#16 0x55fac8024594 <unknown>
#17 0x55fac7feaeef <unknown>
#18 0x55fac8048d98 <unknown>
#19 0x55fac8048f76 <unknown>
#20 0x55fac8059b36 <unknown>
#21 0x7fb668e9caa4 <unknown>
#22 0x7fb668f29c3c <unknown>

ERROR    root:VerifyPersonalizationAndCapture.py:18 ‚ùå Error attaching screenshot to Allure: [Errno 2] No such file or directory: '/home/runner/work/QA-App-Allure/QA-App-Allure/Tests/BFV1_attempt_1.png'