ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJpdGVtQWN0aW9uIjoiVmlldyBJdGVtIiwiY2F0YWxvZyI6eyJJdGVtQ2xhc3MiOnsiX2lkIjoib3ZlcnZpZXcifX0sInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiNjE2Mzk2MjYuMTc0NTQzODg2OSJ9LCJhbm9uSWQiOiJlODYzMmMxZDU4Njc5MzEzIn0sInNvdXJjZSI6eyJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL2NvdXBlL2NsZS9vdmVydmlldy5odG1sIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI2MyIsImNvbnRlbnRab25lcyI6W119LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJfdG9vbHNFdmVudExpbmtJZCI6IjQ4NjM3ODY5MjY3NDczNTY2IiwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfX0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x561bedc65cea <unknown>
#1 0x561bed7165f0 <unknown>
#2 0x561bed6fce86 <unknown>
#3 0x561bed6fb79a <unknown>
#4 0x561bed6fbeff <unknown>
#5 0x561bed6fbe54 <unknown>
#6 0x561bed71a7ff <unknown>
#7 0x561bed7bf9aa <unknown>
#8 0x561bed78d662 <unknown>
#9 0x561bed7b3660 <unknown>
#10 0x561bed78d433 <unknown>
#11 0x561bed759ea3 <unknown>
#12 0x561bed75ab01 <unknown>
#13 0x561bedc2ab3b <unknown>
#14 0x561bedc2ea21 <unknown>
#15 0x561bedc11c32 <unknown>
#16 0x561bedc2f594 <unknown>
#17 0x561bedbf5eef <unknown>
#18 0x561bedc53d98 <unknown>
#19 0x561bedc53f76 <unknown>
#20 0x561bedc64b36 <unknown>
#21 0x7f78e3e9caa4 <unknown>
#22 0x7f78e3f29c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gb3ZlcnZpZXciLCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjYxNjM5NjI2LjE3NDU0Mzg4NjkifSwiYW5vbklkIjoiZTg2MzJjMWQ1ODY3OTMxMyJ9LCJzb3VyY2UiOnsidXJsIjoiaHR0cHM6Ly93d3cubWVyY2VkZXMtYmVuei5pdC9wYXNzZW5nZXJjYXJzL21vZGVscy9jb3VwZS9jbGUvb3ZlcnZpZXcuaHRtbCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjMiLCJjb250ZW50Wm9uZXMiOltdfSwiY29uc2VudHMiOltdLCJhY2NvdW50Ijp7fSwicGVyZm9ybWFuY2UiOnsic2RrUGFyc2VUaW1lIjoyfSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiI3NjY1Nzg4NDI3MjY0NjE3IiwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfX0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x561bedc65cea <unknown>
#1 0x561bed7165f0 <unknown>
#2 0x561bed6fce86 <unknown>
#3 0x561bed6fb79a <unknown>
#4 0x561bed6fbeff <unknown>
#5 0x561bed6fbe54 <unknown>
#6 0x561bed71a7ff <unknown>
#7 0x561bed7bf9aa <unknown>
#8 0x561bed78d662 <unknown>
#9 0x561bed7b3660 <unknown>
#10 0x561bed78d433 <unknown>
#11 0x561bed759ea3 <unknown>
#12 0x561bed75ab01 <unknown>
#13 0x561bedc2ab3b <unknown>
#14 0x561bedc2ea21 <unknown>
#15 0x561bedc11c32 <unknown>
#16 0x561bedc2f594 <unknown>
#17 0x561bedbf5eef <unknown>
#18 0x561bedc53d98 <unknown>
#19 0x561bedc53f76 <unknown>
#20 0x561bedc64b36 <unknown>
#21 0x7f78e3e9caa4 <unknown>
#22 0x7f78e3f29c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJQcm9kdWN0IEluZm9ybWF0aW9uIFBhZ2UgLSBvdmVydmlldyAyMzYzIiwiaXRlbUFjdGlvbiI6IlZpZXcgSXRlbSIsInNvdXJjZSI6eyJwYWdlVHlwZSI6InByb2R1Y3RfaW5mb3JtYXRpb24iLCJsb2NhbGUiOiJpdF9JVCIsImNvbnRlbnRab25lcyI6WyJnbG9iYWxfUElfTkwiLCJwaV9iYW5uZXJfTkwiLCJlcXMtc3BlY2lhbF9OTCJdLCJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL2NvdXBlL2NsZS9vdmVydmlldy5odG1sIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI2MyJ9LCJmbGFncyI6eyJwYWdlVmlldyI6dHJ1ZX0sInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiNjE2Mzk2MjYuMTc0NTQzODg2OSJ9LCJhbm9uSWQiOiJlODYzMmMxZDU4Njc5MzEzIn0sInBlcmZvcm1hbmNlIjp7InNka1BhcnNlVGltZSI6Mn0sImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX0sImNhdGFsb2ciOnsiUHJvZHVjdCI6eyJfaWQiOiIyMzYzIiwiZGltZW5zaW9ucyI6eyJCYXVtdXN0ZXJTaG9ydCI6WyIyMzYzIl19fX0sImNvbnNlbnRzIjpbXSwiYWNjb3VudCI6e30sIl90b29sc0V2ZW50TGlua0lkIjoiODE2NzQwNzc4NDc5NDgyMSJ9: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x561bedc65cea <unknown>
#1 0x561bed7165f0 <unknown>
#2 0x561bed6fce86 <unknown>
#3 0x561bed6fb79a <unknown>
#4 0x561bed6fbeff <unknown>
#5 0x561bed6fbe54 <unknown>
#6 0x561bed71a7ff <unknown>
#7 0x561bed7bf9aa <unknown>
#8 0x561bed78d662 <unknown>
#9 0x561bed7b3660 <unknown>
#10 0x561bed78d433 <unknown>
#11 0x561bed759ea3 <unknown>
#12 0x561bed75ab01 <unknown>
#13 0x561bedc2ab3b <unknown>
#14 0x561bedc2ea21 <unknown>
#15 0x561bedc11c32 <unknown>
#16 0x561bedc2f594 <unknown>
#17 0x561bedbf5eef <unknown>
#18 0x561bedc53d98 <unknown>
#19 0x561bedc53f76 <unknown>
#20 0x561bedc64b36 <unknown>
#21 0x7f78e3e9caa4 <unknown>
#22 0x7f78e3f29c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJzZXRfdXNlcl9hdHRyaWJ1dGUiLCJhY2NvdW50Ijp7ImF0dHJpYnV0ZXMiOnsibGFzdFBpUGFnZSI6eyJ2ZWhpY2xlUEkiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL2NvdXBlL2NsZS9vdmVydmlldy5odG1sIiwidmVoaWNsZUNvZGUiOiJjMjM2IiwidmVoaWNsZUJNIjoiMjM2MyIsInZlaGljbGVQSUhpc3RvcnkiOiIyMzYzIiwidGltZXN0YW1wIjoxNzQ1NDM4ODczMDEyLCJleHBpcmF0aW9uIjoxMjB9fX0sInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiNjE2Mzk2MjYuMTc0NTQzODg2OSJ9LCJhbm9uSWQiOiJlODYzMmMxZDU4Njc5MzEzIn0sInNvdXJjZSI6eyJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL2NvdXBlL2NsZS9vdmVydmlldy5odG1sIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI2MyIsImNvbnRlbnRab25lcyI6W119LCJjb25zZW50cyI6W10sIl90b29sc0V2ZW50TGlua0lkIjoiNzIwNzE4NDY2MzI3MzM3NCIsImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX19: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x561bedc65cea <unknown>
#1 0x561bed7165f0 <unknown>
#2 0x561bed6fce86 <unknown>
#3 0x561bed6fb79a <unknown>
#4 0x561bed6fbeff <unknown>
#5 0x561bed6fbe54 <unknown>
#6 0x561bed71a7ff <unknown>
#7 0x561bed7bf9aa <unknown>
#8 0x561bed78d662 <unknown>
#9 0x561bed7b3660 <unknown>
#10 0x561bed78d433 <unknown>
#11 0x561bed759ea3 <unknown>
#12 0x561bed75ab01 <unknown>
#13 0x561bedc2ab3b <unknown>
#14 0x561bedc2ea21 <unknown>
#15 0x561bedc11c32 <unknown>
#16 0x561bedc2f594 <unknown>
#17 0x561bedbf5eef <unknown>
#18 0x561bedc53d98 <unknown>
#19 0x561bedc53f76 <unknown>
#20 0x561bedc64b36 <unknown>
#21 0x7f78e3e9caa4 <unknown>
#22 0x7f78e3f29c3c <unknown>

ERROR    root:VerifyPersonalizationAndCapture.py:18 ‚ùå Error attaching screenshot to Allure: [Errno 2] No such file or directory: '/home/runner/work/QA-App-Allure/QA-App-Allure/Tests/BFV1_attempt_1.png'