ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJpdGVtQWN0aW9uIjoiVmlldyBJdGVtIiwiY2F0YWxvZyI6eyJJdGVtQ2xhc3MiOnsiX2lkIjoib3ZlcnZpZXcifX0sInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiODM2NjQyNDM1LjE3NDU0NDEzNjIifSwiYW5vbklkIjoiODBiNzIwMTNjMDBmZDhkNyJ9LCJzb3VyY2UiOnsidXJsIjoiaHR0cHM6Ly93d3cubWVyY2VkZXMtYmVuei5pdC9wYXNzZW5nZXJjYXJzL21vZGVscy9lc3RhdGUvZS1jbGFzcy9vdmVydmlldy5odG1sIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI2MyIsImNvbnRlbnRab25lcyI6W119LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJfdG9vbHNFdmVudExpbmtJZCI6IjA5ODY0NTk3OTkzMjM1MjkxIiwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfX0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x556f7ac9ccea <unknown>
#1 0x556f7a74d5f0 <unknown>
#2 0x556f7a733e86 <unknown>
#3 0x556f7a73279a <unknown>
#4 0x556f7a732eff <unknown>
#5 0x556f7a732e54 <unknown>
#6 0x556f7a7517ff <unknown>
#7 0x556f7a7f69aa <unknown>
#8 0x556f7a7c4662 <unknown>
#9 0x556f7a7ea660 <unknown>
#10 0x556f7a7c4433 <unknown>
#11 0x556f7a790ea3 <unknown>
#12 0x556f7a791b01 <unknown>
#13 0x556f7ac61b3b <unknown>
#14 0x556f7ac65a21 <unknown>
#15 0x556f7ac48c32 <unknown>
#16 0x556f7ac66594 <unknown>
#17 0x556f7ac2ceef <unknown>
#18 0x556f7ac8ad98 <unknown>
#19 0x556f7ac8af76 <unknown>
#20 0x556f7ac9bb36 <unknown>
#21 0x7fbd26a9caa4 <unknown>
#22 0x7fbd26b29c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJQcm9kdWN0IEluZm9ybWF0aW9uIFBhZ2UgLSBvdmVydmlldyAyMTQyIiwiaXRlbUFjdGlvbiI6IlZpZXcgSXRlbSIsInNvdXJjZSI6eyJwYWdlVHlwZSI6InByb2R1Y3RfaW5mb3JtYXRpb24iLCJsb2NhbGUiOiJpdF9JVCIsImNvbnRlbnRab25lcyI6WyJnbG9iYWxfUElfTkwiLCJwaV9iYW5uZXJfTkwiLCJlcXMtc3BlY2lhbF9OTCJdLCJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL2VzdGF0ZS9lLWNsYXNzL292ZXJ2aWV3Lmh0bWwiLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjYzIn0sImZsYWdzIjp7InBhZ2VWaWV3Ijp0cnVlfSwidXNlciI6eyJhdHRyaWJ1dGVzIjp7ImdhQ2xpZW50SUQiOiI4MzY2NDI0MzUuMTc0NTQ0MTM2MiJ9LCJhbm9uSWQiOiI4MGI3MjAxM2MwMGZkOGQ3In0sInBlcmZvcm1hbmNlIjp7fSwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfSwiY2F0YWxvZyI6eyJQcm9kdWN0Ijp7Il9pZCI6IjIxNDIiLCJkaW1lbnNpb25zIjp7IkJhdW11c3RlclNob3J0IjpbIjIxNDIiXX19fSwiY29uc2VudHMiOltdLCJhY2NvdW50Ijp7fSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiI2MzE0NzQ1Nzc1NzkzMzY5In0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x556f7ac9ccea <unknown>
#1 0x556f7a74d5f0 <unknown>
#2 0x556f7a733e86 <unknown>
#3 0x556f7a73279a <unknown>
#4 0x556f7a732eff <unknown>
#5 0x556f7a732e54 <unknown>
#6 0x556f7a7517ff <unknown>
#7 0x556f7a7f69aa <unknown>
#8 0x556f7a7c4662 <unknown>
#9 0x556f7a7ea660 <unknown>
#10 0x556f7a7c4433 <unknown>
#11 0x556f7a790ea3 <unknown>
#12 0x556f7a791b01 <unknown>
#13 0x556f7ac61b3b <unknown>
#14 0x556f7ac65a21 <unknown>
#15 0x556f7ac48c32 <unknown>
#16 0x556f7ac66594 <unknown>
#17 0x556f7ac2ceef <unknown>
#18 0x556f7ac8ad98 <unknown>
#19 0x556f7ac8af76 <unknown>
#20 0x556f7ac9bb36 <unknown>
#21 0x7fbd26a9caa4 <unknown>
#22 0x7fbd26b29c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gb3ZlcnZpZXciLCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjgzNjY0MjQzNS4xNzQ1NDQxMzYyIn0sImFub25JZCI6IjgwYjcyMDEzYzAwZmQ4ZDcifSwic291cmNlIjp7InVybCI6Imh0dHBzOi8vd3d3Lm1lcmNlZGVzLWJlbnouaXQvcGFzc2VuZ2VyY2Fycy9tb2RlbHMvZXN0YXRlL2UtY2xhc3Mvb3ZlcnZpZXcuaHRtbCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjMiLCJjb250ZW50Wm9uZXMiOltdfSwiY29uc2VudHMiOltdLCJhY2NvdW50Ijp7fSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiI4NDU2MjkxNDEwMDM4MTk2IiwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfX0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x556f7ac9ccea <unknown>
#1 0x556f7a74d5f0 <unknown>
#2 0x556f7a733e86 <unknown>
#3 0x556f7a73279a <unknown>
#4 0x556f7a732eff <unknown>
#5 0x556f7a732e54 <unknown>
#6 0x556f7a7517ff <unknown>
#7 0x556f7a7f69aa <unknown>
#8 0x556f7a7c4662 <unknown>
#9 0x556f7a7ea660 <unknown>
#10 0x556f7a7c4433 <unknown>
#11 0x556f7a790ea3 <unknown>
#12 0x556f7a791b01 <unknown>
#13 0x556f7ac61b3b <unknown>
#14 0x556f7ac65a21 <unknown>
#15 0x556f7ac48c32 <unknown>
#16 0x556f7ac66594 <unknown>
#17 0x556f7ac2ceef <unknown>
#18 0x556f7ac8ad98 <unknown>
#19 0x556f7ac8af76 <unknown>
#20 0x556f7ac9bb36 <unknown>
#21 0x7fbd26a9caa4 <unknown>
#22 0x7fbd26b29c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJzZXRfdXNlcl9hdHRyaWJ1dGUiLCJhY2NvdW50Ijp7ImF0dHJpYnV0ZXMiOnsibGFzdFBpUGFnZSI6eyJ2ZWhpY2xlUEkiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL2VzdGF0ZS9lLWNsYXNzL292ZXJ2aWV3Lmh0bWwiLCJ2ZWhpY2xlQ29kZSI6InMyMTQiLCJ2ZWhpY2xlQk0iOiIyMTQyIiwidmVoaWNsZVBJSGlzdG9yeSI6IjIxNDIiLCJ0aW1lc3RhbXAiOjE3NDU0NDEzNjY0MTUsImV4cGlyYXRpb24iOjEyMH19fSwidXNlciI6eyJhdHRyaWJ1dGVzIjp7ImdhQ2xpZW50SUQiOiI4MzY2NDI0MzUuMTc0NTQ0MTM2MiJ9LCJhbm9uSWQiOiI4MGI3MjAxM2MwMGZkOGQ3In0sInNvdXJjZSI6eyJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL2VzdGF0ZS9lLWNsYXNzL292ZXJ2aWV3Lmh0bWwiLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjYzIiwiY29udGVudFpvbmVzIjpbXX0sImNvbnNlbnRzIjpbXSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiIyMTE0OTgxOTMzODkwNDQzIiwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfX0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x556f7ac9ccea <unknown>
#1 0x556f7a74d5f0 <unknown>
#2 0x556f7a733e86 <unknown>
#3 0x556f7a73279a <unknown>
#4 0x556f7a732eff <unknown>
#5 0x556f7a732e54 <unknown>
#6 0x556f7a7517ff <unknown>
#7 0x556f7a7f69aa <unknown>
#8 0x556f7a7c4662 <unknown>
#9 0x556f7a7ea660 <unknown>
#10 0x556f7a7c4433 <unknown>
#11 0x556f7a790ea3 <unknown>
#12 0x556f7a791b01 <unknown>
#13 0x556f7ac61b3b <unknown>
#14 0x556f7ac65a21 <unknown>
#15 0x556f7ac48c32 <unknown>
#16 0x556f7ac66594 <unknown>
#17 0x556f7ac2ceef <unknown>
#18 0x556f7ac8ad98 <unknown>
#19 0x556f7ac8af76 <unknown>
#20 0x556f7ac9bb36 <unknown>
#21 0x7fbd26a9caa4 <unknown>
#22 0x7fbd26b29c3c <unknown>

ERROR    root:VerifyPersonalizationAndCapture.py:18 ‚ùå Error attaching screenshot to Allure: [Errno 2] No such file or directory: '/home/runner/work/QA-App-Allure/QA-App-Allure/Tests/BFV1_attempt_1.png'