ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJpdGVtQWN0aW9uIjoiVmlldyBJdGVtIiwiY2F0YWxvZyI6eyJJdGVtQ2xhc3MiOnsiX2lkIjoib3ZlcnZpZXcifX0sInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiODkyMDMxNzkxLjE3NDU0MzkwMzUifSwiYW5vbklkIjoiZDllM2RiM2I4NGZmYjZiMCJ9LCJzb3VyY2UiOnsidXJsIjoiaHR0cHM6Ly93d3cubWVyY2VkZXMtYmVuei5pdC9wYXNzZW5nZXJjYXJzL21vZGVscy9zdXYvZ2xiL292ZXJ2aWV3Lmh0bWwiLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjYzIiwiY29udGVudFpvbmVzIjpbXX0sImNvbnNlbnRzIjpbXSwiYWNjb3VudCI6e30sIl90b29sc0V2ZW50TGlua0lkIjoiNjU2NTI4MDE3MzAzMDE0IiwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfX0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x559e2025fcea <unknown>
#1 0x559e1fd105f0 <unknown>
#2 0x559e1fcf6e86 <unknown>
#3 0x559e1fcf579a <unknown>
#4 0x559e1fcf5eff <unknown>
#5 0x559e1fcf5e54 <unknown>
#6 0x559e1fd147ff <unknown>
#7 0x559e1fdb99aa <unknown>
#8 0x559e1fd87662 <unknown>
#9 0x559e1fdad660 <unknown>
#10 0x559e1fd87433 <unknown>
#11 0x559e1fd53ea3 <unknown>
#12 0x559e1fd54b01 <unknown>
#13 0x559e20224b3b <unknown>
#14 0x559e20228a21 <unknown>
#15 0x559e2020bc32 <unknown>
#16 0x559e20229594 <unknown>
#17 0x559e201efeef <unknown>
#18 0x559e2024dd98 <unknown>
#19 0x559e2024df76 <unknown>
#20 0x559e2025eb36 <unknown>
#21 0x7fdb42a9caa4 <unknown>
#22 0x7fdb42b29c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJQcm9kdWN0IEluZm9ybWF0aW9uIFBhZ2UgLSBvdmVydmlldyAyNDc2IiwiaXRlbUFjdGlvbiI6IlZpZXcgSXRlbSIsInNvdXJjZSI6eyJwYWdlVHlwZSI6InByb2R1Y3RfaW5mb3JtYXRpb24iLCJsb2NhbGUiOiJpdF9JVCIsImNvbnRlbnRab25lcyI6WyJnbG9iYWxfUElfTkwiLCJwaV9iYW5uZXJfTkwiLCJlcXMtc3BlY2lhbF9OTCJdLCJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9nbGIvb3ZlcnZpZXcuaHRtbCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNjMifSwiZmxhZ3MiOnsicGFnZVZpZXciOnRydWV9LCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6Ijg5MjAzMTc5MS4xNzQ1NDM5MDM1In0sImFub25JZCI6ImQ5ZTNkYjNiODRmZmI2YjAifSwicGVyZm9ybWFuY2UiOnsic2RrUGFyc2VUaW1lIjoxfSwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfSwiY2F0YWxvZyI6eyJQcm9kdWN0Ijp7Il9pZCI6IjI0NzYiLCJkaW1lbnNpb25zIjp7IkJhdW11c3RlclNob3J0IjpbIjI0NzYiXX19fSwiY29uc2VudHMiOltdLCJhY2NvdW50Ijp7fSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiI0NTc4Njc4MjY2MzQzODkyIn0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x559e2025fcea <unknown>
#1 0x559e1fd105f0 <unknown>
#2 0x559e1fcf6e86 <unknown>
#3 0x559e1fcf579a <unknown>
#4 0x559e1fcf5eff <unknown>
#5 0x559e1fcf5e54 <unknown>
#6 0x559e1fd147ff <unknown>
#7 0x559e1fdb99aa <unknown>
#8 0x559e1fd87662 <unknown>
#9 0x559e1fdad660 <unknown>
#10 0x559e1fd87433 <unknown>
#11 0x559e1fd53ea3 <unknown>
#12 0x559e1fd54b01 <unknown>
#13 0x559e20224b3b <unknown>
#14 0x559e20228a21 <unknown>
#15 0x559e2020bc32 <unknown>
#16 0x559e20229594 <unknown>
#17 0x559e201efeef <unknown>
#18 0x559e2024dd98 <unknown>
#19 0x559e2024df76 <unknown>
#20 0x559e2025eb36 <unknown>
#21 0x7fdb42a9caa4 <unknown>
#22 0x7fdb42b29c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gb3ZlcnZpZXciLCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6Ijg5MjAzMTc5MS4xNzQ1NDM5MDM1In0sImFub25JZCI6ImQ5ZTNkYjNiODRmZmI2YjAifSwic291cmNlIjp7InVybCI6Imh0dHBzOi8vd3d3Lm1lcmNlZGVzLWJlbnouaXQvcGFzc2VuZ2VyY2Fycy9tb2RlbHMvc3V2L2dsYi9vdmVydmlldy5odG1sIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI2MyIsImNvbnRlbnRab25lcyI6W119LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJwZXJmb3JtYW5jZSI6eyJzZGtQYXJzZVRpbWUiOjF9LCJfdG9vbHNFdmVudExpbmtJZCI6IjUxMjAwMTMxOTg4NjYyOSIsImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX19: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x559e2025fcea <unknown>
#1 0x559e1fd105f0 <unknown>
#2 0x559e1fcf6e86 <unknown>
#3 0x559e1fcf579a <unknown>
#4 0x559e1fcf5eff <unknown>
#5 0x559e1fcf5e54 <unknown>
#6 0x559e1fd147ff <unknown>
#7 0x559e1fdb99aa <unknown>
#8 0x559e1fd87662 <unknown>
#9 0x559e1fdad660 <unknown>
#10 0x559e1fd87433 <unknown>
#11 0x559e1fd53ea3 <unknown>
#12 0x559e1fd54b01 <unknown>
#13 0x559e20224b3b <unknown>
#14 0x559e20228a21 <unknown>
#15 0x559e2020bc32 <unknown>
#16 0x559e20229594 <unknown>
#17 0x559e201efeef <unknown>
#18 0x559e2024dd98 <unknown>
#19 0x559e2024df76 <unknown>
#20 0x559e2025eb36 <unknown>
#21 0x7fdb42a9caa4 <unknown>
#22 0x7fdb42b29c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJzZXRfdXNlcl9hdHRyaWJ1dGUiLCJhY2NvdW50Ijp7ImF0dHJpYnV0ZXMiOnsibGFzdFBpUGFnZSI6eyJ2ZWhpY2xlUEkiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9nbGIvb3ZlcnZpZXcuaHRtbCIsInZlaGljbGVDb2RlIjoieDI0Ny1mbCIsInZlaGljbGVCTSI6IjI0NzYiLCJ2ZWhpY2xlUElIaXN0b3J5IjoiMjQ3NiIsInRpbWVzdGFtcCI6MTc0NTQzOTAzODk4MCwiZXhwaXJhdGlvbiI6MTIwfX19LCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6Ijg5MjAzMTc5MS4xNzQ1NDM5MDM1In0sImFub25JZCI6ImQ5ZTNkYjNiODRmZmI2YjAifSwic291cmNlIjp7InVybCI6Imh0dHBzOi8vd3d3Lm1lcmNlZGVzLWJlbnouaXQvcGFzc2VuZ2VyY2Fycy9tb2RlbHMvc3V2L2dsYi9vdmVydmlldy5odG1sIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI2MyIsImNvbnRlbnRab25lcyI6W119LCJjb25zZW50cyI6W10sIl90b29sc0V2ZW50TGlua0lkIjoiODA2Mzg0OTE5MzgyMDIzNCIsImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX19: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x559e2025fcea <unknown>
#1 0x559e1fd105f0 <unknown>
#2 0x559e1fcf6e86 <unknown>
#3 0x559e1fcf579a <unknown>
#4 0x559e1fcf5eff <unknown>
#5 0x559e1fcf5e54 <unknown>
#6 0x559e1fd147ff <unknown>
#7 0x559e1fdb99aa <unknown>
#8 0x559e1fd87662 <unknown>
#9 0x559e1fdad660 <unknown>
#10 0x559e1fd87433 <unknown>
#11 0x559e1fd53ea3 <unknown>
#12 0x559e1fd54b01 <unknown>
#13 0x559e20224b3b <unknown>
#14 0x559e20228a21 <unknown>
#15 0x559e2020bc32 <unknown>
#16 0x559e20229594 <unknown>
#17 0x559e201efeef <unknown>
#18 0x559e2024dd98 <unknown>
#19 0x559e2024df76 <unknown>
#20 0x559e2025eb36 <unknown>
#21 0x7fdb42a9caa4 <unknown>
#22 0x7fdb42b29c3c <unknown>

ERROR    root:VerifyPersonalizationAndCapture.py:18 ‚ùå Error attaching screenshot to Allure: [Errno 2] No such file or directory: '/home/runner/work/QA-App-Allure/QA-App-Allure/Tests/BFV1_attempt_1.png'