ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJpdGVtQWN0aW9uIjoiVmlldyBJdGVtIiwiY2F0YWxvZyI6eyJJdGVtQ2xhc3MiOnsiX2lkIjoib3ZlcnZpZXcifX0sInNvdXJjZSI6eyJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL2VzdGF0ZS9lLWNsYXNzL292ZXJ2aWV3Lmh0bWwiLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjYzIiwiY29udGVudFpvbmVzIjpbXX0sInVzZXIiOnsiYW5vbklkIjoiNmQ1ZGIwZTkxZDIzMWIwNiJ9LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJfdG9vbHNFdmVudExpbmtJZCI6IjMwNTk1MjgxNTcwNDMwOTU0IiwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfX0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x559820604cea <unknown>
#1 0x5598200b55f0 <unknown>
#2 0x55982009be86 <unknown>
#3 0x55982009a79a <unknown>
#4 0x55982009aeff <unknown>
#5 0x55982009ae54 <unknown>
#6 0x5598200b97ff <unknown>
#7 0x55982015e9aa <unknown>
#8 0x55982012c662 <unknown>
#9 0x559820152660 <unknown>
#10 0x55982012c433 <unknown>
#11 0x5598200f8ea3 <unknown>
#12 0x5598200f9b01 <unknown>
#13 0x5598205c9b3b <unknown>
#14 0x5598205cda21 <unknown>
#15 0x5598205b0c32 <unknown>
#16 0x5598205ce594 <unknown>
#17 0x559820594eef <unknown>
#18 0x5598205f2d98 <unknown>
#19 0x5598205f2f76 <unknown>
#20 0x559820603b36 <unknown>
#21 0x7fa6fe49caa4 <unknown>
#22 0x7fa6fe529c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJQcm9kdWN0IEluZm9ybWF0aW9uIFBhZ2UgLSBvdmVydmlldyAyMTQyIiwiaXRlbUFjdGlvbiI6IlZpZXcgSXRlbSIsInNvdXJjZSI6eyJwYWdlVHlwZSI6InByb2R1Y3RfaW5mb3JtYXRpb24iLCJsb2NhbGUiOiJpdF9JVCIsImNvbnRlbnRab25lcyI6WyJnbG9iYWxfUElfTkwiLCJwaV9iYW5uZXJfTkwiLCJlcXMtc3BlY2lhbF9OTCJdLCJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL2VzdGF0ZS9lLWNsYXNzL292ZXJ2aWV3Lmh0bWwiLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjYzIn0sImZsYWdzIjp7InBhZ2VWaWV3Ijp0cnVlfSwidXNlciI6eyJhbm9uSWQiOiI2ZDVkYjBlOTFkMjMxYjA2In0sInBlcmZvcm1hbmNlIjp7InNka1BhcnNlVGltZSI6MX0sImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX0sImNhdGFsb2ciOnsiUHJvZHVjdCI6eyJfaWQiOiIyMTQyIiwiZGltZW5zaW9ucyI6eyJCYXVtdXN0ZXJTaG9ydCI6WyIyMTQyIl19fX0sImNvbnNlbnRzIjpbXSwiYWNjb3VudCI6e30sIl90b29sc0V2ZW50TGlua0lkIjoiMDMwOTY1NDYzODczMzk1MjcifQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x559820604cea <unknown>
#1 0x5598200b55f0 <unknown>
#2 0x55982009be86 <unknown>
#3 0x55982009a79a <unknown>
#4 0x55982009aeff <unknown>
#5 0x55982009ae54 <unknown>
#6 0x5598200b97ff <unknown>
#7 0x55982015e9aa <unknown>
#8 0x55982012c662 <unknown>
#9 0x559820152660 <unknown>
#10 0x55982012c433 <unknown>
#11 0x5598200f8ea3 <unknown>
#12 0x5598200f9b01 <unknown>
#13 0x5598205c9b3b <unknown>
#14 0x5598205cda21 <unknown>
#15 0x5598205b0c32 <unknown>
#16 0x5598205ce594 <unknown>
#17 0x559820594eef <unknown>
#18 0x5598205f2d98 <unknown>
#19 0x5598205f2f76 <unknown>
#20 0x559820603b36 <unknown>
#21 0x7fa6fe49caa4 <unknown>
#22 0x7fa6fe529c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gb3ZlcnZpZXciLCJzb3VyY2UiOnsidXJsIjoiaHR0cHM6Ly93d3cubWVyY2VkZXMtYmVuei5pdC9wYXNzZW5nZXJjYXJzL21vZGVscy9lc3RhdGUvZS1jbGFzcy9vdmVydmlldy5odG1sIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI2MyIsImNvbnRlbnRab25lcyI6W119LCJ1c2VyIjp7ImFub25JZCI6IjZkNWRiMGU5MWQyMzFiMDYifSwiY29uc2VudHMiOltdLCJhY2NvdW50Ijp7fSwicGVyZm9ybWFuY2UiOnsic2RrUGFyc2VUaW1lIjoxfSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiIxOTY1MDg5MjY3OTM0MDUzNyIsImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX19: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x559820604cea <unknown>
#1 0x5598200b55f0 <unknown>
#2 0x55982009be86 <unknown>
#3 0x55982009a79a <unknown>
#4 0x55982009aeff <unknown>
#5 0x55982009ae54 <unknown>
#6 0x5598200b97ff <unknown>
#7 0x55982015e9aa <unknown>
#8 0x55982012c662 <unknown>
#9 0x559820152660 <unknown>
#10 0x55982012c433 <unknown>
#11 0x5598200f8ea3 <unknown>
#12 0x5598200f9b01 <unknown>
#13 0x5598205c9b3b <unknown>
#14 0x5598205cda21 <unknown>
#15 0x5598205b0c32 <unknown>
#16 0x5598205ce594 <unknown>
#17 0x559820594eef <unknown>
#18 0x5598205f2d98 <unknown>
#19 0x5598205f2f76 <unknown>
#20 0x559820603b36 <unknown>
#21 0x7fa6fe49caa4 <unknown>
#22 0x7fa6fe529c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJzZXRfdXNlcl9hdHRyaWJ1dGUiLCJhY2NvdW50Ijp7ImF0dHJpYnV0ZXMiOnsibGFzdFBpUGFnZSI6eyJ2ZWhpY2xlUEkiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL2VzdGF0ZS9lLWNsYXNzL292ZXJ2aWV3Lmh0bWwiLCJ2ZWhpY2xlQ29kZSI6InMyMTQiLCJ2ZWhpY2xlQk0iOiIyMTQyIiwidmVoaWNsZVBJSGlzdG9yeSI6IjIxNDIiLCJ0aW1lc3RhbXAiOjE3NDU0Mzk4MjE1NDksImV4cGlyYXRpb24iOjEyMH19fSwidXNlciI6eyJhdHRyaWJ1dGVzIjp7ImdhQ2xpZW50SUQiOiIxNzg0MzYwNDY1LjE3NDU0Mzk4MTkifSwiYW5vbklkIjoiNmQ1ZGIwZTkxZDIzMWIwNiJ9LCJzb3VyY2UiOnsidXJsIjoiaHR0cHM6Ly93d3cubWVyY2VkZXMtYmVuei5pdC9wYXNzZW5nZXJjYXJzL21vZGVscy9lc3RhdGUvZS1jbGFzcy9vdmVydmlldy5odG1sIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI2MyIsImNvbnRlbnRab25lcyI6W119LCJjb25zZW50cyI6W10sIl90b29sc0V2ZW50TGlua0lkIjoiMDg2MDQ2NzIwNTk1MTkyMzYiLCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9fQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x559820604cea <unknown>
#1 0x5598200b55f0 <unknown>
#2 0x55982009be86 <unknown>
#3 0x55982009a79a <unknown>
#4 0x55982009aeff <unknown>
#5 0x55982009ae54 <unknown>
#6 0x5598200b97ff <unknown>
#7 0x55982015e9aa <unknown>
#8 0x55982012c662 <unknown>
#9 0x559820152660 <unknown>
#10 0x55982012c433 <unknown>
#11 0x5598200f8ea3 <unknown>
#12 0x5598200f9b01 <unknown>
#13 0x5598205c9b3b <unknown>
#14 0x5598205cda21 <unknown>
#15 0x5598205b0c32 <unknown>
#16 0x5598205ce594 <unknown>
#17 0x559820594eef <unknown>
#18 0x5598205f2d98 <unknown>
#19 0x5598205f2f76 <unknown>
#20 0x559820603b36 <unknown>
#21 0x7fa6fe49caa4 <unknown>
#22 0x7fa6fe529c3c <unknown>

ERROR    root:VerifyPersonalizationAndCapture.py:111 ❌ Image not found in the specified selector. Error: Message: 

ERROR    root:VerifyPersonalizationAndCapture.py:18 ❌ Error attaching screenshot to Allure: [Errno 2] No such file or directory: '/home/runner/work/QA-App-Allure/QA-App-Allure/Tests/BFV1_attempt_1.png'
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f73b8bea1d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/efd81d66de77f3bb46a5a77e1d48e965
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f73b8be98d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/efd81d66de77f3bb46a5a77e1d48e965
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f73b8be8d90>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/efd81d66de77f3bb46a5a77e1d48e965
ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJQcm9kdWN0IEluZm9ybWF0aW9uIFBhZ2UgLSBvdmVydmlldyAyMTQyIiwiaXRlbUFjdGlvbiI6IlZpZXcgSXRlbSIsInNvdXJjZSI6eyJwYWdlVHlwZSI6InByb2R1Y3RfaW5mb3JtYXRpb24iLCJsb2NhbGUiOiJpdF9JVCIsImNvbnRlbnRab25lcyI6WyJnbG9iYWxfUElfTkwiLCJwaV9iYW5uZXJfTkwiLCJlcXMtc3BlY2lhbF9OTCJdLCJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL2VzdGF0ZS9lLWNsYXNzL292ZXJ2aWV3Lmh0bWwiLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjYzIn0sImZsYWdzIjp7InBhZ2VWaWV3Ijp0cnVlfSwidXNlciI6eyJhbm9uSWQiOiIzNGYyMTk0MDg1ZTc5YmFmIn0sInBlcmZvcm1hbmNlIjp7InNka1BhcnNlVGltZSI6MX0sImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX0sImNhdGFsb2ciOnsiUHJvZHVjdCI6eyJfaWQiOiIyMTQyIiwiZGltZW5zaW9ucyI6eyJCYXVtdXN0ZXJTaG9ydCI6WyIyMTQyIl19fX0sImNvbnNlbnRzIjpbXSwiYWNjb3VudCI6e30sIl90b29sc0V2ZW50TGlua0lkIjoiNTg2NDM2MDk1MTkyNzUzOSJ9: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x55dd82467cea <unknown>
#1 0x55dd81f185f0 <unknown>
#2 0x55dd81efee86 <unknown>
#3 0x55dd81efd79a <unknown>
#4 0x55dd81efdeff <unknown>
#5 0x55dd81efde54 <unknown>
#6 0x55dd81f1c7ff <unknown>
#7 0x55dd81fc19aa <unknown>
#8 0x55dd81f8f662 <unknown>
#9 0x55dd81fb5660 <unknown>
#10 0x55dd81f8f433 <unknown>
#11 0x55dd81f5bea3 <unknown>
#12 0x55dd81f5cb01 <unknown>
#13 0x55dd8242cb3b <unknown>
#14 0x55dd82430a21 <unknown>
#15 0x55dd82413c32 <unknown>
#16 0x55dd82431594 <unknown>
#17 0x55dd823f7eef <unknown>
#18 0x55dd82455d98 <unknown>
#19 0x55dd82455f76 <unknown>
#20 0x55dd82466b36 <unknown>
#21 0x7f31a609caa4 <unknown>
#22 0x7f31a6129c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gb3ZlcnZpZXciLCJzb3VyY2UiOnsidXJsIjoiaHR0cHM6Ly93d3cubWVyY2VkZXMtYmVuei5pdC9wYXNzZW5nZXJjYXJzL21vZGVscy9lc3RhdGUvZS1jbGFzcy9vdmVydmlldy5odG1sIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI2MyIsImNvbnRlbnRab25lcyI6W119LCJ1c2VyIjp7ImFub25JZCI6IjM0ZjIxOTQwODVlNzliYWYifSwiY29uc2VudHMiOltdLCJhY2NvdW50Ijp7fSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiIyMjI3MzgwNTA2NjE1NTc1IiwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfX0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x55dd82467cea <unknown>
#1 0x55dd81f185f0 <unknown>
#2 0x55dd81efee86 <unknown>
#3 0x55dd81efd79a <unknown>
#4 0x55dd81efdeff <unknown>
#5 0x55dd81efde54 <unknown>
#6 0x55dd81f1c7ff <unknown>
#7 0x55dd81fc19aa <unknown>
#8 0x55dd81f8f662 <unknown>
#9 0x55dd81fb5660 <unknown>
#10 0x55dd81f8f433 <unknown>
#11 0x55dd81f5bea3 <unknown>
#12 0x55dd81f5cb01 <unknown>
#13 0x55dd8242cb3b <unknown>
#14 0x55dd82430a21 <unknown>
#15 0x55dd82413c32 <unknown>
#16 0x55dd82431594 <unknown>
#17 0x55dd823f7eef <unknown>
#18 0x55dd82455d98 <unknown>
#19 0x55dd82455f76 <unknown>
#20 0x55dd82466b36 <unknown>
#21 0x7f31a609caa4 <unknown>
#22 0x7f31a6129c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJpdGVtQWN0aW9uIjoiVmlldyBJdGVtIiwiY2F0YWxvZyI6eyJJdGVtQ2xhc3MiOnsiX2lkIjoib3ZlcnZpZXcifX0sInNvdXJjZSI6eyJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL2VzdGF0ZS9lLWNsYXNzL292ZXJ2aWV3Lmh0bWwiLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjYzIiwiY29udGVudFpvbmVzIjpbXX0sInVzZXIiOnsiYW5vbklkIjoiMzRmMjE5NDA4NWU3OWJhZiJ9LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJwZXJmb3JtYW5jZSI6eyJzZGtQYXJzZVRpbWUiOjF9LCJfdG9vbHNFdmVudExpbmtJZCI6IjE2NDU1MTE4NTYzNjI5NSIsImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX19: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x55dd82467cea <unknown>
#1 0x55dd81f185f0 <unknown>
#2 0x55dd81efee86 <unknown>
#3 0x55dd81efd79a <unknown>
#4 0x55dd81efdeff <unknown>
#5 0x55dd81efde54 <unknown>
#6 0x55dd81f1c7ff <unknown>
#7 0x55dd81fc19aa <unknown>
#8 0x55dd81f8f662 <unknown>
#9 0x55dd81fb5660 <unknown>
#10 0x55dd81f8f433 <unknown>
#11 0x55dd81f5bea3 <unknown>
#12 0x55dd81f5cb01 <unknown>
#13 0x55dd8242cb3b <unknown>
#14 0x55dd82430a21 <unknown>
#15 0x55dd82413c32 <unknown>
#16 0x55dd82431594 <unknown>
#17 0x55dd823f7eef <unknown>
#18 0x55dd82455d98 <unknown>
#19 0x55dd82455f76 <unknown>
#20 0x55dd82466b36 <unknown>
#21 0x7f31a609caa4 <unknown>
#22 0x7f31a6129c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJzZXRfdXNlcl9hdHRyaWJ1dGUiLCJhY2NvdW50Ijp7ImF0dHJpYnV0ZXMiOnsibGFzdFBpUGFnZSI6eyJ2ZWhpY2xlUEkiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL2VzdGF0ZS9lLWNsYXNzL292ZXJ2aWV3Lmh0bWwiLCJ2ZWhpY2xlQ29kZSI6InMyMTQiLCJ2ZWhpY2xlQk0iOiIyMTQyIiwidmVoaWNsZVBJSGlzdG9yeSI6IjIxNDIiLCJ0aW1lc3RhbXAiOjE3NDU0Mzk4NTQ3NjgsImV4cGlyYXRpb24iOjEyMH19fSwidXNlciI6eyJhdHRyaWJ1dGVzIjp7ImdhQ2xpZW50SUQiOiIxMDMzNDExOTcuMTc0NTQzOTg1MyJ9LCJhbm9uSWQiOiIzNGYyMTk0MDg1ZTc5YmFmIn0sInNvdXJjZSI6eyJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL2VzdGF0ZS9lLWNsYXNzL292ZXJ2aWV3Lmh0bWwiLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjYzIiwiY29udGVudFpvbmVzIjpbXX0sImNvbnNlbnRzIjpbXSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiIwMjExOTMyMzY5MDIwNTEzMjciLCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9fQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x55dd82467cea <unknown>
#1 0x55dd81f185f0 <unknown>
#2 0x55dd81efee86 <unknown>
#3 0x55dd81efd79a <unknown>
#4 0x55dd81efdeff <unknown>
#5 0x55dd81efde54 <unknown>
#6 0x55dd81f1c7ff <unknown>
#7 0x55dd81fc19aa <unknown>
#8 0x55dd81f8f662 <unknown>
#9 0x55dd81fb5660 <unknown>
#10 0x55dd81f8f433 <unknown>
#11 0x55dd81f5bea3 <unknown>
#12 0x55dd81f5cb01 <unknown>
#13 0x55dd8242cb3b <unknown>
#14 0x55dd82430a21 <unknown>
#15 0x55dd82413c32 <unknown>
#16 0x55dd82431594 <unknown>
#17 0x55dd823f7eef <unknown>
#18 0x55dd82455d98 <unknown>
#19 0x55dd82455f76 <unknown>
#20 0x55dd82466b36 <unknown>
#21 0x7f31a609caa4 <unknown>
#22 0x7f31a6129c3c <unknown>

ERROR    root:VerifyPersonalizationAndCapture.py:111 ❌ Image not found in the specified selector. Error: Message: 

ERROR    root:VerifyPersonalizationAndCapture.py:18 ❌ Error attaching screenshot to Allure: [Errno 2] No such file or directory: '/home/runner/work/QA-App-Allure/QA-App-Allure/Tests/BFV1_attempt_2.png'
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f73b8beed50>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/adb06f41f71c5878c176169bea821acd
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f73b8bef4d0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/adb06f41f71c5878c176169bea821acd
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f73b88dc710>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/adb06f41f71c5878c176169bea821acd
ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gb3ZlcnZpZXciLCJzb3VyY2UiOnsidXJsIjoiaHR0cHM6Ly93d3cubWVyY2VkZXMtYmVuei5pdC9wYXNzZW5nZXJjYXJzL21vZGVscy9lc3RhdGUvZS1jbGFzcy9vdmVydmlldy5odG1sIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI2MyIsImNvbnRlbnRab25lcyI6W119LCJ1c2VyIjp7ImFub25JZCI6ImRlY2QyYmNmMDE4ZGE2ZmMifSwiY29uc2VudHMiOltdLCJhY2NvdW50Ijp7fSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiIzMDM3MTg1ODY4ODY1NTk5NSIsImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX19: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x555e080eacea <unknown>
#1 0x555e07b9b5f0 <unknown>
#2 0x555e07b81e86 <unknown>
#3 0x555e07b8079a <unknown>
#4 0x555e07b80eff <unknown>
#5 0x555e07b80e54 <unknown>
#6 0x555e07b9f7ff <unknown>
#7 0x555e07c449aa <unknown>
#8 0x555e07c12662 <unknown>
#9 0x555e07c38660 <unknown>
#10 0x555e07c12433 <unknown>
#11 0x555e07bdeea3 <unknown>
#12 0x555e07bdfb01 <unknown>
#13 0x555e080afb3b <unknown>
#14 0x555e080b3a21 <unknown>
#15 0x555e08096c32 <unknown>
#16 0x555e080b4594 <unknown>
#17 0x555e0807aeef <unknown>
#18 0x555e080d8d98 <unknown>
#19 0x555e080d8f76 <unknown>
#20 0x555e080e9b36 <unknown>
#21 0x7f6e4449caa4 <unknown>
#22 0x7f6e44529c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJpdGVtQWN0aW9uIjoiVmlldyBJdGVtIiwiY2F0YWxvZyI6eyJJdGVtQ2xhc3MiOnsiX2lkIjoib3ZlcnZpZXcifX0sInNvdXJjZSI6eyJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL2VzdGF0ZS9lLWNsYXNzL292ZXJ2aWV3Lmh0bWwiLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjYzIiwiY29udGVudFpvbmVzIjpbXX0sInVzZXIiOnsiYW5vbklkIjoiZGVjZDJiY2YwMThkYTZmYyJ9LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJwZXJmb3JtYW5jZSI6eyJzZGtQYXJzZVRpbWUiOjF9LCJfdG9vbHNFdmVudExpbmtJZCI6Ijc4Nzk3NDk3ODUzMjAwODIiLCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9fQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x555e080eacea <unknown>
#1 0x555e07b9b5f0 <unknown>
#2 0x555e07b81e86 <unknown>
#3 0x555e07b8079a <unknown>
#4 0x555e07b80eff <unknown>
#5 0x555e07b80e54 <unknown>
#6 0x555e07b9f7ff <unknown>
#7 0x555e07c449aa <unknown>
#8 0x555e07c12662 <unknown>
#9 0x555e07c38660 <unknown>
#10 0x555e07c12433 <unknown>
#11 0x555e07bdeea3 <unknown>
#12 0x555e07bdfb01 <unknown>
#13 0x555e080afb3b <unknown>
#14 0x555e080b3a21 <unknown>
#15 0x555e08096c32 <unknown>
#16 0x555e080b4594 <unknown>
#17 0x555e0807aeef <unknown>
#18 0x555e080d8d98 <unknown>
#19 0x555e080d8f76 <unknown>
#20 0x555e080e9b36 <unknown>
#21 0x7f6e4449caa4 <unknown>
#22 0x7f6e44529c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJQcm9kdWN0IEluZm9ybWF0aW9uIFBhZ2UgLSBvdmVydmlldyAyMTQyIiwiaXRlbUFjdGlvbiI6IlZpZXcgSXRlbSIsInNvdXJjZSI6eyJwYWdlVHlwZSI6InByb2R1Y3RfaW5mb3JtYXRpb24iLCJsb2NhbGUiOiJpdF9JVCIsImNvbnRlbnRab25lcyI6WyJnbG9iYWxfUElfTkwiLCJwaV9iYW5uZXJfTkwiLCJlcXMtc3BlY2lhbF9OTCJdLCJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL2VzdGF0ZS9lLWNsYXNzL292ZXJ2aWV3Lmh0bWwiLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjYzIn0sImZsYWdzIjp7InBhZ2VWaWV3Ijp0cnVlfSwidXNlciI6eyJhbm9uSWQiOiJkZWNkMmJjZjAxOGRhNmZjIn0sInBlcmZvcm1hbmNlIjp7InNka1BhcnNlVGltZSI6MX0sImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX0sImNhdGFsb2ciOnsiUHJvZHVjdCI6eyJfaWQiOiIyMTQyIiwiZGltZW5zaW9ucyI6eyJCYXVtdXN0ZXJTaG9ydCI6WyIyMTQyIl19fX0sImNvbnNlbnRzIjpbXSwiYWNjb3VudCI6e30sIl90b29sc0V2ZW50TGlua0lkIjoiNjkxMDcxODg4NTMyMzEyOSJ9: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x555e080eacea <unknown>
#1 0x555e07b9b5f0 <unknown>
#2 0x555e07b81e86 <unknown>
#3 0x555e07b8079a <unknown>
#4 0x555e07b80eff <unknown>
#5 0x555e07b80e54 <unknown>
#6 0x555e07b9f7ff <unknown>
#7 0x555e07c449aa <unknown>
#8 0x555e07c12662 <unknown>
#9 0x555e07c38660 <unknown>
#10 0x555e07c12433 <unknown>
#11 0x555e07bdeea3 <unknown>
#12 0x555e07bdfb01 <unknown>
#13 0x555e080afb3b <unknown>
#14 0x555e080b3a21 <unknown>
#15 0x555e08096c32 <unknown>
#16 0x555e080b4594 <unknown>
#17 0x555e0807aeef <unknown>
#18 0x555e080d8d98 <unknown>
#19 0x555e080d8f76 <unknown>
#20 0x555e080e9b36 <unknown>
#21 0x7f6e4449caa4 <unknown>
#22 0x7f6e44529c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJzZXRfdXNlcl9hdHRyaWJ1dGUiLCJhY2NvdW50Ijp7ImF0dHJpYnV0ZXMiOnsibGFzdFBpUGFnZSI6eyJ2ZWhpY2xlUEkiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL2VzdGF0ZS9lLWNsYXNzL292ZXJ2aWV3Lmh0bWwiLCJ2ZWhpY2xlQ29kZSI6InMyMTQiLCJ2ZWhpY2xlQk0iOiIyMTQyIiwidmVoaWNsZVBJSGlzdG9yeSI6IjIxNDIiLCJ0aW1lc3RhbXAiOjE3NDU0Mzk4ODk1MjQsImV4cGlyYXRpb24iOjEyMH19fSwidXNlciI6eyJhdHRyaWJ1dGVzIjp7ImdhQ2xpZW50SUQiOiIxNzUzODUxMDk0LjE3NDU0Mzk4ODcifSwiYW5vbklkIjoiZGVjZDJiY2YwMThkYTZmYyJ9LCJzb3VyY2UiOnsidXJsIjoiaHR0cHM6Ly93d3cubWVyY2VkZXMtYmVuei5pdC9wYXNzZW5nZXJjYXJzL21vZGVscy9lc3RhdGUvZS1jbGFzcy9vdmVydmlldy5odG1sIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI2MyIsImNvbnRlbnRab25lcyI6W119LCJjb25zZW50cyI6W10sIl90b29sc0V2ZW50TGlua0lkIjoiMjM0ODY4MDQ0OTYxMDMwOTgiLCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9fQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x555e080eacea <unknown>
#1 0x555e07b9b5f0 <unknown>
#2 0x555e07b81e86 <unknown>
#3 0x555e07b8079a <unknown>
#4 0x555e07b80eff <unknown>
#5 0x555e07b80e54 <unknown>
#6 0x555e07b9f7ff <unknown>
#7 0x555e07c449aa <unknown>
#8 0x555e07c12662 <unknown>
#9 0x555e07c38660 <unknown>
#10 0x555e07c12433 <unknown>
#11 0x555e07bdeea3 <unknown>
#12 0x555e07bdfb01 <unknown>
#13 0x555e080afb3b <unknown>
#14 0x555e080b3a21 <unknown>
#15 0x555e08096c32 <unknown>
#16 0x555e080b4594 <unknown>
#17 0x555e0807aeef <unknown>
#18 0x555e080d8d98 <unknown>
#19 0x555e080d8f76 <unknown>
#20 0x555e080e9b36 <unknown>
#21 0x7f6e4449caa4 <unknown>
#22 0x7f6e44529c3c <unknown>

ERROR    root:VerifyPersonalizationAndCapture.py:111 ❌ Image not found in the specified selector. Error: Message: 

ERROR    root:VerifyPersonalizationAndCapture.py:18 ❌ Error attaching screenshot to Allure: [Errno 2] No such file or directory: '/home/runner/work/QA-App-Allure/QA-App-Allure/Tests/BFV1_attempt_3.png'
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f73b6797250>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/4dca2eebd77ded0a9b36705e272ae3f3
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f73b6794550>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/4dca2eebd77ded0a9b36705e272ae3f3
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f73b6794f50>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/4dca2eebd77ded0a9b36705e272ae3f3
ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJQcm9kdWN0IEluZm9ybWF0aW9uIFBhZ2UgLSBvdmVydmlldyAyMTQyIiwiaXRlbUFjdGlvbiI6IlZpZXcgSXRlbSIsInNvdXJjZSI6eyJwYWdlVHlwZSI6InByb2R1Y3RfaW5mb3JtYXRpb24iLCJsb2NhbGUiOiJpdF9JVCIsImNvbnRlbnRab25lcyI6WyJnbG9iYWxfUElfTkwiLCJwaV9iYW5uZXJfTkwiLCJlcXMtc3BlY2lhbF9OTCJdLCJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL2VzdGF0ZS9lLWNsYXNzL292ZXJ2aWV3Lmh0bWwiLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjYzIn0sImZsYWdzIjp7InBhZ2VWaWV3Ijp0cnVlfSwidXNlciI6eyJhbm9uSWQiOiI1M2MwNjJlOWM2ZGE5NjMzIn0sInBlcmZvcm1hbmNlIjp7InNka1BhcnNlVGltZSI6MX0sImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX0sImNhdGFsb2ciOnsiUHJvZHVjdCI6eyJfaWQiOiIyMTQyIiwiZGltZW5zaW9ucyI6eyJCYXVtdXN0ZXJTaG9ydCI6WyIyMTQyIl19fX0sImNvbnNlbnRzIjpbXSwiYWNjb3VudCI6e30sIl90b29sc0V2ZW50TGlua0lkIjoiNzA1NTkyNTQxNTI3NzgyNSJ9: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x5638b7e9acea <unknown>
#1 0x5638b794b5f0 <unknown>
#2 0x5638b7931e86 <unknown>
#3 0x5638b793079a <unknown>
#4 0x5638b7930eff <unknown>
#5 0x5638b7930e54 <unknown>
#6 0x5638b794f7ff <unknown>
#7 0x5638b79f49aa <unknown>
#8 0x5638b79c2662 <unknown>
#9 0x5638b79e8660 <unknown>
#10 0x5638b79c2433 <unknown>
#11 0x5638b798eea3 <unknown>
#12 0x5638b798fb01 <unknown>
#13 0x5638b7e5fb3b <unknown>
#14 0x5638b7e63a21 <unknown>
#15 0x5638b7e46c32 <unknown>
#16 0x5638b7e64594 <unknown>
#17 0x5638b7e2aeef <unknown>
#18 0x5638b7e88d98 <unknown>
#19 0x5638b7e88f76 <unknown>
#20 0x5638b7e99b36 <unknown>
#21 0x7f080b49caa4 <unknown>
#22 0x7f080b529c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJpdGVtQWN0aW9uIjoiVmlldyBJdGVtIiwiY2F0YWxvZyI6eyJJdGVtQ2xhc3MiOnsiX2lkIjoib3ZlcnZpZXcifX0sInNvdXJjZSI6eyJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL2VzdGF0ZS9lLWNsYXNzL292ZXJ2aWV3Lmh0bWwiLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjYzIiwiY29udGVudFpvbmVzIjpbXX0sInVzZXIiOnsiYW5vbklkIjoiNTNjMDYyZTljNmRhOTYzMyJ9LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJfdG9vbHNFdmVudExpbmtJZCI6IjA3MTQ3MDQzNTE2MjMzNzc1IiwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfX0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x5638b7e9acea <unknown>
#1 0x5638b794b5f0 <unknown>
#2 0x5638b7931e86 <unknown>
#3 0x5638b793079a <unknown>
#4 0x5638b7930eff <unknown>
#5 0x5638b7930e54 <unknown>
#6 0x5638b794f7ff <unknown>
#7 0x5638b79f49aa <unknown>
#8 0x5638b79c2662 <unknown>
#9 0x5638b79e8660 <unknown>
#10 0x5638b79c2433 <unknown>
#11 0x5638b798eea3 <unknown>
#12 0x5638b798fb01 <unknown>
#13 0x5638b7e5fb3b <unknown>
#14 0x5638b7e63a21 <unknown>
#15 0x5638b7e46c32 <unknown>
#16 0x5638b7e64594 <unknown>
#17 0x5638b7e2aeef <unknown>
#18 0x5638b7e88d98 <unknown>
#19 0x5638b7e88f76 <unknown>
#20 0x5638b7e99b36 <unknown>
#21 0x7f080b49caa4 <unknown>
#22 0x7f080b529c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gb3ZlcnZpZXciLCJzb3VyY2UiOnsidXJsIjoiaHR0cHM6Ly93d3cubWVyY2VkZXMtYmVuei5pdC9wYXNzZW5nZXJjYXJzL21vZGVscy9lc3RhdGUvZS1jbGFzcy9vdmVydmlldy5odG1sIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI2MyIsImNvbnRlbnRab25lcyI6W119LCJ1c2VyIjp7ImFub25JZCI6IjUzYzA2MmU5YzZkYTk2MzMifSwiY29uc2VudHMiOltdLCJhY2NvdW50Ijp7fSwicGVyZm9ybWFuY2UiOnsic2RrUGFyc2VUaW1lIjoxfSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiI2MDE5OTA2MDgzODEwNDExIiwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfX0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x5638b7e9acea <unknown>
#1 0x5638b794b5f0 <unknown>
#2 0x5638b7931e86 <unknown>
#3 0x5638b793079a <unknown>
#4 0x5638b7930eff <unknown>
#5 0x5638b7930e54 <unknown>
#6 0x5638b794f7ff <unknown>
#7 0x5638b79f49aa <unknown>
#8 0x5638b79c2662 <unknown>
#9 0x5638b79e8660 <unknown>
#10 0x5638b79c2433 <unknown>
#11 0x5638b798eea3 <unknown>
#12 0x5638b798fb01 <unknown>
#13 0x5638b7e5fb3b <unknown>
#14 0x5638b7e63a21 <unknown>
#15 0x5638b7e46c32 <unknown>
#16 0x5638b7e64594 <unknown>
#17 0x5638b7e2aeef <unknown>
#18 0x5638b7e88d98 <unknown>
#19 0x5638b7e88f76 <unknown>
#20 0x5638b7e99b36 <unknown>
#21 0x7f080b49caa4 <unknown>
#22 0x7f080b529c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJzZXRfdXNlcl9hdHRyaWJ1dGUiLCJhY2NvdW50Ijp7ImF0dHJpYnV0ZXMiOnsibGFzdFBpUGFnZSI6eyJ2ZWhpY2xlUEkiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL2VzdGF0ZS9lLWNsYXNzL292ZXJ2aWV3Lmh0bWwiLCJ2ZWhpY2xlQ29kZSI6InMyMTQiLCJ2ZWhpY2xlQk0iOiIyMTQyIiwidmVoaWNsZVBJSGlzdG9yeSI6IjIxNDIiLCJ0aW1lc3RhbXAiOjE3NDU0Mzk5MjM1NTMsImV4cGlyYXRpb24iOjEyMH19fSwidXNlciI6eyJhdHRyaWJ1dGVzIjp7ImdhQ2xpZW50SUQiOiIxNzY0OTY5MjMxLjE3NDU0Mzk5MjEifSwiYW5vbklkIjoiNTNjMDYyZTljNmRhOTYzMyJ9LCJzb3VyY2UiOnsidXJsIjoiaHR0cHM6Ly93d3cubWVyY2VkZXMtYmVuei5pdC9wYXNzZW5nZXJjYXJzL21vZGVscy9lc3RhdGUvZS1jbGFzcy9vdmVydmlldy5odG1sIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI2MyIsImNvbnRlbnRab25lcyI6W119LCJjb25zZW50cyI6W10sIl90b29sc0V2ZW50TGlua0lkIjoiNzU3MTg4MDMzMjAwOTgiLCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9fQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x5638b7e9acea <unknown>
#1 0x5638b794b5f0 <unknown>
#2 0x5638b7931e86 <unknown>
#3 0x5638b793079a <unknown>
#4 0x5638b7930eff <unknown>
#5 0x5638b7930e54 <unknown>
#6 0x5638b794f7ff <unknown>
#7 0x5638b79f49aa <unknown>
#8 0x5638b79c2662 <unknown>
#9 0x5638b79e8660 <unknown>
#10 0x5638b79c2433 <unknown>
#11 0x5638b798eea3 <unknown>
#12 0x5638b798fb01 <unknown>
#13 0x5638b7e5fb3b <unknown>
#14 0x5638b7e63a21 <unknown>
#15 0x5638b7e46c32 <unknown>
#16 0x5638b7e64594 <unknown>
#17 0x5638b7e2aeef <unknown>
#18 0x5638b7e88d98 <unknown>
#19 0x5638b7e88f76 <unknown>
#20 0x5638b7e99b36 <unknown>
#21 0x7f080b49caa4 <unknown>
#22 0x7f080b529c3c <unknown>

ERROR    root:VerifyPersonalizationAndCapture.py:111 ❌ Image not found in the specified selector. Error: Message: 

ERROR    root:VerifyPersonalizationAndCapture.py:18 ❌ Error attaching screenshot to Allure: [Errno 2] No such file or directory: '/home/runner/work/QA-App-Allure/QA-App-Allure/Tests/BFV1_attempt_4.png'
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f73b7bc5710>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/fca1bc9d7cd5b61dc3e00816793399f7
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f73b7bc7c90>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/fca1bc9d7cd5b61dc3e00816793399f7
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f73b7bc7ad0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/fca1bc9d7cd5b61dc3e00816793399f7
ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJpdGVtQWN0aW9uIjoiVmlldyBJdGVtIiwiY2F0YWxvZyI6eyJJdGVtQ2xhc3MiOnsiX2lkIjoib3ZlcnZpZXcifX0sInNvdXJjZSI6eyJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL2VzdGF0ZS9lLWNsYXNzL292ZXJ2aWV3Lmh0bWwiLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjYzIiwiY29udGVudFpvbmVzIjpbXX0sInVzZXIiOnsiYW5vbklkIjoiZWI2MDMxZTBlNjE2MWRlZCJ9LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJfdG9vbHNFdmVudExpbmtJZCI6IjUwMzI5NjA0MTgxMDY4NDUiLCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9fQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x55a099364cea <unknown>
#1 0x55a098e155f0 <unknown>
#2 0x55a098dfbe86 <unknown>
#3 0x55a098dfa79a <unknown>
#4 0x55a098dfaeff <unknown>
#5 0x55a098dfae54 <unknown>
#6 0x55a098e197ff <unknown>
#7 0x55a098ebe9aa <unknown>
#8 0x55a098e8c662 <unknown>
#9 0x55a098eb2660 <unknown>
#10 0x55a098e8c433 <unknown>
#11 0x55a098e58ea3 <unknown>
#12 0x55a098e59b01 <unknown>
#13 0x55a099329b3b <unknown>
#14 0x55a09932da21 <unknown>
#15 0x55a099310c32 <unknown>
#16 0x55a09932e594 <unknown>
#17 0x55a0992f4eef <unknown>
#18 0x55a099352d98 <unknown>
#19 0x55a099352f76 <unknown>
#20 0x55a099363b36 <unknown>
#21 0x7f719689caa4 <unknown>
#22 0x7f7196929c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJQcm9kdWN0IEluZm9ybWF0aW9uIFBhZ2UgLSBvdmVydmlldyAyMTQyIiwiaXRlbUFjdGlvbiI6IlZpZXcgSXRlbSIsInNvdXJjZSI6eyJwYWdlVHlwZSI6InByb2R1Y3RfaW5mb3JtYXRpb24iLCJsb2NhbGUiOiJpdF9JVCIsImNvbnRlbnRab25lcyI6WyJnbG9iYWxfUElfTkwiLCJwaV9iYW5uZXJfTkwiLCJlcXMtc3BlY2lhbF9OTCJdLCJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL2VzdGF0ZS9lLWNsYXNzL292ZXJ2aWV3Lmh0bWwiLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjYzIn0sImZsYWdzIjp7InBhZ2VWaWV3Ijp0cnVlfSwidXNlciI6eyJhbm9uSWQiOiJlYjYwMzFlMGU2MTYxZGVkIn0sInBlcmZvcm1hbmNlIjp7InNka1BhcnNlVGltZSI6MX0sImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX0sImNhdGFsb2ciOnsiUHJvZHVjdCI6eyJfaWQiOiIyMTQyIiwiZGltZW5zaW9ucyI6eyJCYXVtdXN0ZXJTaG9ydCI6WyIyMTQyIl19fX0sImNvbnNlbnRzIjpbXSwiYWNjb3VudCI6e30sIl90b29sc0V2ZW50TGlua0lkIjoiMjQxOTY2NTgxNzAzNDg4OTUifQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x55a099364cea <unknown>
#1 0x55a098e155f0 <unknown>
#2 0x55a098dfbe86 <unknown>
#3 0x55a098dfa79a <unknown>
#4 0x55a098dfaeff <unknown>
#5 0x55a098dfae54 <unknown>
#6 0x55a098e197ff <unknown>
#7 0x55a098ebe9aa <unknown>
#8 0x55a098e8c662 <unknown>
#9 0x55a098eb2660 <unknown>
#10 0x55a098e8c433 <unknown>
#11 0x55a098e58ea3 <unknown>
#12 0x55a098e59b01 <unknown>
#13 0x55a099329b3b <unknown>
#14 0x55a09932da21 <unknown>
#15 0x55a099310c32 <unknown>
#16 0x55a09932e594 <unknown>
#17 0x55a0992f4eef <unknown>
#18 0x55a099352d98 <unknown>
#19 0x55a099352f76 <unknown>
#20 0x55a099363b36 <unknown>
#21 0x7f719689caa4 <unknown>
#22 0x7f7196929c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gb3ZlcnZpZXciLCJzb3VyY2UiOnsidXJsIjoiaHR0cHM6Ly93d3cubWVyY2VkZXMtYmVuei5pdC9wYXNzZW5nZXJjYXJzL21vZGVscy9lc3RhdGUvZS1jbGFzcy9vdmVydmlldy5odG1sIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI2MyIsImNvbnRlbnRab25lcyI6W119LCJ1c2VyIjp7ImFub25JZCI6ImViNjAzMWUwZTYxNjFkZWQifSwiY29uc2VudHMiOltdLCJhY2NvdW50Ijp7fSwicGVyZm9ybWFuY2UiOnsic2RrUGFyc2VUaW1lIjoxfSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiI2MDczMTc1OTkwNzg5MTUxIiwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfX0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x55a099364cea <unknown>
#1 0x55a098e155f0 <unknown>
#2 0x55a098dfbe86 <unknown>
#3 0x55a098dfa79a <unknown>
#4 0x55a098dfaeff <unknown>
#5 0x55a098dfae54 <unknown>
#6 0x55a098e197ff <unknown>
#7 0x55a098ebe9aa <unknown>
#8 0x55a098e8c662 <unknown>
#9 0x55a098eb2660 <unknown>
#10 0x55a098e8c433 <unknown>
#11 0x55a098e58ea3 <unknown>
#12 0x55a098e59b01 <unknown>
#13 0x55a099329b3b <unknown>
#14 0x55a09932da21 <unknown>
#15 0x55a099310c32 <unknown>
#16 0x55a09932e594 <unknown>
#17 0x55a0992f4eef <unknown>
#18 0x55a099352d98 <unknown>
#19 0x55a099352f76 <unknown>
#20 0x55a099363b36 <unknown>
#21 0x7f719689caa4 <unknown>
#22 0x7f7196929c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJzZXRfdXNlcl9hdHRyaWJ1dGUiLCJhY2NvdW50Ijp7ImF0dHJpYnV0ZXMiOnsibGFzdFBpUGFnZSI6eyJ2ZWhpY2xlUEkiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL2VzdGF0ZS9lLWNsYXNzL292ZXJ2aWV3Lmh0bWwiLCJ2ZWhpY2xlQ29kZSI6InMyMTQiLCJ2ZWhpY2xlQk0iOiIyMTQyIiwidmVoaWNsZVBJSGlzdG9yeSI6IjIxNDIiLCJ0aW1lc3RhbXAiOjE3NDU0Mzk5NTY0NTAsImV4cGlyYXRpb24iOjEyMH19fSwidXNlciI6eyJhdHRyaWJ1dGVzIjp7ImdhQ2xpZW50SUQiOiIyMDc5MDk4MzMzLjE3NDU0Mzk5NTUifSwiYW5vbklkIjoiZWI2MDMxZTBlNjE2MWRlZCJ9LCJzb3VyY2UiOnsidXJsIjoiaHR0cHM6Ly93d3cubWVyY2VkZXMtYmVuei5pdC9wYXNzZW5nZXJjYXJzL21vZGVscy9lc3RhdGUvZS1jbGFzcy9vdmVydmlldy5odG1sIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI2MyIsImNvbnRlbnRab25lcyI6W119LCJjb25zZW50cyI6W10sIl90b29sc0V2ZW50TGlua0lkIjoiNzAyOTU5NDAzNzY1Nzg3NyIsImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX19: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x55a099364cea <unknown>
#1 0x55a098e155f0 <unknown>
#2 0x55a098dfbe86 <unknown>
#3 0x55a098dfa79a <unknown>
#4 0x55a098dfaeff <unknown>
#5 0x55a098dfae54 <unknown>
#6 0x55a098e197ff <unknown>
#7 0x55a098ebe9aa <unknown>
#8 0x55a098e8c662 <unknown>
#9 0x55a098eb2660 <unknown>
#10 0x55a098e8c433 <unknown>
#11 0x55a098e58ea3 <unknown>
#12 0x55a098e59b01 <unknown>
#13 0x55a099329b3b <unknown>
#14 0x55a09932da21 <unknown>
#15 0x55a099310c32 <unknown>
#16 0x55a09932e594 <unknown>
#17 0x55a0992f4eef <unknown>
#18 0x55a099352d98 <unknown>
#19 0x55a099352f76 <unknown>
#20 0x55a099363b36 <unknown>
#21 0x7f719689caa4 <unknown>
#22 0x7f7196929c3c <unknown>

ERROR    root:VerifyPersonalizationAndCapture.py:18 ❌ Error attaching screenshot to Allure: [Errno 2] No such file or directory: '/home/runner/work/QA-App-Allure/QA-App-Allure/Tests/BFV1_attempt_5.png'
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f73b7c8a910>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/efd81d66de77f3bb46a5a77e1d48e965
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f73b7c88450>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/efd81d66de77f3bb46a5a77e1d48e965
WARNING  urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f73b7c8ba90>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/efd81d66de77f3bb46a5a77e1d48e965