ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJpdGVtQWN0aW9uIjoiVmlldyBJdGVtIiwiY2F0YWxvZyI6eyJJdGVtQ2xhc3MiOnsiX2lkIjoib3ZlcnZpZXcifX0sInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiMTIzMTYxOTIzMy4xNzQ1NDMyMTQ5In0sImFub25JZCI6IjVmYTg4M2Q4ZmQzNjg4MjQifSwic291cmNlIjp7InVybCI6Imh0dHBzOi8vd3d3Lm1lcmNlZGVzLWJlbnouaXQvcGFzc2VuZ2VyY2Fycy9tb2RlbHMvY291cGUvY2xlL292ZXJ2aWV3Lmh0bWwiLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjYzIiwiY29udGVudFpvbmVzIjpbXX0sImNvbnNlbnRzIjpbXSwiYWNjb3VudCI6e30sIl90b29sc0V2ZW50TGlua0lkIjoiMjM3NzQxNTgyNTY0ODYyMSIsImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX19: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x563084217cea <unknown>
#1 0x563083cc85f0 <unknown>
#2 0x563083caee86 <unknown>
#3 0x563083cad79a <unknown>
#4 0x563083cadeff <unknown>
#5 0x563083cade54 <unknown>
#6 0x563083ccc7ff <unknown>
#7 0x563083d719aa <unknown>
#8 0x563083d3f662 <unknown>
#9 0x563083d65660 <unknown>
#10 0x563083d3f433 <unknown>
#11 0x563083d0bea3 <unknown>
#12 0x563083d0cb01 <unknown>
#13 0x5630841dcb3b <unknown>
#14 0x5630841e0a21 <unknown>
#15 0x5630841c3c32 <unknown>
#16 0x5630841e1594 <unknown>
#17 0x5630841a7eef <unknown>
#18 0x563084205d98 <unknown>
#19 0x563084205f76 <unknown>
#20 0x563084216b36 <unknown>
#21 0x7fefad09caa4 <unknown>
#22 0x7fefad129c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJQcm9kdWN0IEluZm9ybWF0aW9uIFBhZ2UgLSBvdmVydmlldyAyMzYzIiwiaXRlbUFjdGlvbiI6IlZpZXcgSXRlbSIsInNvdXJjZSI6eyJwYWdlVHlwZSI6InByb2R1Y3RfaW5mb3JtYXRpb24iLCJsb2NhbGUiOiJpdF9JVCIsImNvbnRlbnRab25lcyI6WyJnbG9iYWxfUElfTkwiLCJwaV9iYW5uZXJfTkwiLCJlcXMtc3BlY2lhbF9OTCJdLCJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL2NvdXBlL2NsZS9vdmVydmlldy5odG1sIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI2MyJ9LCJmbGFncyI6eyJwYWdlVmlldyI6dHJ1ZX0sInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiMTIzMTYxOTIzMy4xNzQ1NDMyMTQ5In0sImFub25JZCI6IjVmYTg4M2Q4ZmQzNjg4MjQifSwicGVyZm9ybWFuY2UiOnsic2RrUGFyc2VUaW1lIjoxfSwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfSwiY2F0YWxvZyI6eyJQcm9kdWN0Ijp7Il9pZCI6IjIzNjMiLCJkaW1lbnNpb25zIjp7IkJhdW11c3RlclNob3J0IjpbIjIzNjMiXX19fSwiY29uc2VudHMiOltdLCJhY2NvdW50Ijp7fSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiIyNTkwNjgyNjI0ODg0ODYxMyJ9: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x563084217cea <unknown>
#1 0x563083cc85f0 <unknown>
#2 0x563083caee86 <unknown>
#3 0x563083cad79a <unknown>
#4 0x563083cadeff <unknown>
#5 0x563083cade54 <unknown>
#6 0x563083ccc7ff <unknown>
#7 0x563083d719aa <unknown>
#8 0x563083d3f662 <unknown>
#9 0x563083d65660 <unknown>
#10 0x563083d3f433 <unknown>
#11 0x563083d0bea3 <unknown>
#12 0x563083d0cb01 <unknown>
#13 0x5630841dcb3b <unknown>
#14 0x5630841e0a21 <unknown>
#15 0x5630841c3c32 <unknown>
#16 0x5630841e1594 <unknown>
#17 0x5630841a7eef <unknown>
#18 0x563084205d98 <unknown>
#19 0x563084205f76 <unknown>
#20 0x563084216b36 <unknown>
#21 0x7fefad09caa4 <unknown>
#22 0x7fefad129c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gb3ZlcnZpZXciLCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjEyMzE2MTkyMzMuMTc0NTQzMjE0OSJ9LCJhbm9uSWQiOiI1ZmE4ODNkOGZkMzY4ODI0In0sInNvdXJjZSI6eyJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL2NvdXBlL2NsZS9vdmVydmlldy5odG1sIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI2MyIsImNvbnRlbnRab25lcyI6W119LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJwZXJmb3JtYW5jZSI6eyJzZGtQYXJzZVRpbWUiOjF9LCJfdG9vbHNFdmVudExpbmtJZCI6IjkzNTgyMzc0NjU0MzkxNDkiLCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9fQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x563084217cea <unknown>
#1 0x563083cc85f0 <unknown>
#2 0x563083caee86 <unknown>
#3 0x563083cad79a <unknown>
#4 0x563083cadeff <unknown>
#5 0x563083cade54 <unknown>
#6 0x563083ccc7ff <unknown>
#7 0x563083d719aa <unknown>
#8 0x563083d3f662 <unknown>
#9 0x563083d65660 <unknown>
#10 0x563083d3f433 <unknown>
#11 0x563083d0bea3 <unknown>
#12 0x563083d0cb01 <unknown>
#13 0x5630841dcb3b <unknown>
#14 0x5630841e0a21 <unknown>
#15 0x5630841c3c32 <unknown>
#16 0x5630841e1594 <unknown>
#17 0x5630841a7eef <unknown>
#18 0x563084205d98 <unknown>
#19 0x563084205f76 <unknown>
#20 0x563084216b36 <unknown>
#21 0x7fefad09caa4 <unknown>
#22 0x7fefad129c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_italy_prod?event=eyJhY3Rpb24iOiJzZXRfdXNlcl9hdHRyaWJ1dGUiLCJhY2NvdW50Ijp7ImF0dHJpYnV0ZXMiOnsibGFzdFBpUGFnZSI6eyJ2ZWhpY2xlUEkiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56Lml0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL2NvdXBlL2NsZS9vdmVydmlldy5odG1sIiwidmVoaWNsZUNvZGUiOiJjMjM2IiwidmVoaWNsZUJNIjoiMjM2MyIsInZlaGljbGVQSUhpc3RvcnkiOiIyMzYzIiwidGltZXN0YW1wIjoxNzQ1NDMyMTUzMzExLCJleHBpcmF0aW9uIjoxMjB9fX0sInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiMTIzMTYxOTIzMy4xNzQ1NDMyMTQ5In0sImFub25JZCI6IjVmYTg4M2Q4ZmQzNjg4MjQifSwic291cmNlIjp7InVybCI6Imh0dHBzOi8vd3d3Lm1lcmNlZGVzLWJlbnouaXQvcGFzc2VuZ2VyY2Fycy9tb2RlbHMvY291cGUvY2xlL292ZXJ2aWV3Lmh0bWwiLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjYzIiwiY29udGVudFpvbmVzIjpbXX0sImNvbnNlbnRzIjpbXSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiIwNTM3ODU2NDMwMzc4Nzk4MDQiLCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9fQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x563084217cea <unknown>
#1 0x563083cc85f0 <unknown>
#2 0x563083caee86 <unknown>
#3 0x563083cad79a <unknown>
#4 0x563083cadeff <unknown>
#5 0x563083cade54 <unknown>
#6 0x563083ccc7ff <unknown>
#7 0x563083d719aa <unknown>
#8 0x563083d3f662 <unknown>
#9 0x563083d65660 <unknown>
#10 0x563083d3f433 <unknown>
#11 0x563083d0bea3 <unknown>
#12 0x563083d0cb01 <unknown>
#13 0x5630841dcb3b <unknown>
#14 0x5630841e0a21 <unknown>
#15 0x5630841c3c32 <unknown>
#16 0x5630841e1594 <unknown>
#17 0x5630841a7eef <unknown>
#18 0x563084205d98 <unknown>
#19 0x563084205f76 <unknown>
#20 0x563084216b36 <unknown>
#21 0x7fefad09caa4 <unknown>
#22 0x7fefad129c3c <unknown>

ERROR    root:VerifyPersonalizationAndCapture.py:18 ‚ùå Error attaching screenshot to Allure: [Errno 2] No such file or directory: '/home/runner/work/QA-App-Allure/QA-App-Allure/Tests/BFV1_attempt_1.png'