ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_austria_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gb3ZlcnZpZXciLCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjE0NDI1Mzg1OTguMTc0NjAwMzk4NyJ9LCJhbm9uSWQiOiJhNzYyNWNlMjU5NmQzNmQ1In0sInNvdXJjZSI6eyJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56LmF0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL2NvdXBlL2NsZS9vdmVydmlldy5odG1sIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI3MSIsImNvbnRlbnRab25lcyI6W119LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJfdG9vbHNFdmVudExpbmtJZCI6IjIwMDAxNTAwMDUxMzA1MDY2IiwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfX0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x5633801d5cea <unknown>
#1 0x56337fc865f0 <unknown>
#2 0x56337fc6ce86 <unknown>
#3 0x56337fc6b79a <unknown>
#4 0x56337fc6beff <unknown>
#5 0x56337fc6be54 <unknown>
#6 0x56337fc8a7ff <unknown>
#7 0x56337fd2f9aa <unknown>
#8 0x56337fcfd662 <unknown>
#9 0x56337fd23660 <unknown>
#10 0x56337fcfd433 <unknown>
#11 0x56337fcc9ea3 <unknown>
#12 0x56337fccab01 <unknown>
#13 0x56338019ab3b <unknown>
#14 0x56338019ea21 <unknown>
#15 0x563380181c32 <unknown>
#16 0x56338019f594 <unknown>
#17 0x563380165eef <unknown>
#18 0x5633801c3d98 <unknown>
#19 0x5633801c3f76 <unknown>
#20 0x5633801d4b36 <unknown>
#21 0x7f941f29caa4 <unknown>
#22 0x7f941f329c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_austria_prod?event=eyJhY3Rpb24iOiJQcm9kdWN0IEluZm9ybWF0aW9uIFBhZ2UgLSBvdmVydmlldyAyMzYzIiwiaXRlbUFjdGlvbiI6IlZpZXcgSXRlbSIsInNvdXJjZSI6eyJwYWdlVHlwZSI6InByb2R1Y3RfaW5mb3JtYXRpb24iLCJsb2NhbGUiOiJkZV9BVCIsImNvbnRlbnRab25lcyI6WyJnbG9iYWxfUElfTkwiLCJwaV9iYW5uZXJfTkwiLCJlcXMtc3BlY2lhbF9OTCJdLCJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56LmF0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL2NvdXBlL2NsZS9vdmVydmlldy5odG1sIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI3MSJ9LCJmbGFncyI6eyJwYWdlVmlldyI6dHJ1ZX0sInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiMTQ0MjUzODU5OC4xNzQ2MDAzOTg3In0sImFub25JZCI6ImE3NjI1Y2UyNTk2ZDM2ZDUifSwicGVyZm9ybWFuY2UiOnt9LCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9LCJjYXRhbG9nIjp7IlByb2R1Y3QiOnsiX2lkIjoiMjM2MyIsImRpbWVuc2lvbnMiOnsiQmF1bXVzdGVyU2hvcnQiOlsiMjM2MyJdfX19LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJfdG9vbHNFdmVudExpbmtJZCI6IjI5MzMzMzg4NTEwMzExMTQifQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x5633801d5cea <unknown>
#1 0x56337fc865f0 <unknown>
#2 0x56337fc6ce86 <unknown>
#3 0x56337fc6b79a <unknown>
#4 0x56337fc6beff <unknown>
#5 0x56337fc6be54 <unknown>
#6 0x56337fc8a7ff <unknown>
#7 0x56337fd2f9aa <unknown>
#8 0x56337fcfd662 <unknown>
#9 0x56337fd23660 <unknown>
#10 0x56337fcfd433 <unknown>
#11 0x56337fcc9ea3 <unknown>
#12 0x56337fccab01 <unknown>
#13 0x56338019ab3b <unknown>
#14 0x56338019ea21 <unknown>
#15 0x563380181c32 <unknown>
#16 0x56338019f594 <unknown>
#17 0x563380165eef <unknown>
#18 0x5633801c3d98 <unknown>
#19 0x5633801c3f76 <unknown>
#20 0x5633801d4b36 <unknown>
#21 0x7f941f29caa4 <unknown>
#22 0x7f941f329c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_austria_prod?event=eyJpdGVtQWN0aW9uIjoiVmlldyBJdGVtIiwiY2F0YWxvZyI6eyJJdGVtQ2xhc3MiOnsiX2lkIjoib3ZlcnZpZXcifX0sInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiMTQ0MjUzODU5OC4xNzQ2MDAzOTg3In0sImFub25JZCI6ImE3NjI1Y2UyNTk2ZDM2ZDUifSwic291cmNlIjp7InVybCI6Imh0dHBzOi8vd3d3Lm1lcmNlZGVzLWJlbnouYXQvcGFzc2VuZ2VyY2Fycy9tb2RlbHMvY291cGUvY2xlL292ZXJ2aWV3Lmh0bWwiLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjcxIiwiY29udGVudFpvbmVzIjpbXX0sImNvbnNlbnRzIjpbXSwiYWNjb3VudCI6e30sIl90b29sc0V2ZW50TGlua0lkIjoiNjM4MzEwNDI2NDkzNjU5MSIsImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX19: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x5633801d5cea <unknown>
#1 0x56337fc865f0 <unknown>
#2 0x56337fc6ce86 <unknown>
#3 0x56337fc6b79a <unknown>
#4 0x56337fc6beff <unknown>
#5 0x56337fc6be54 <unknown>
#6 0x56337fc8a7ff <unknown>
#7 0x56337fd2f9aa <unknown>
#8 0x56337fcfd662 <unknown>
#9 0x56337fd23660 <unknown>
#10 0x56337fcfd433 <unknown>
#11 0x56337fcc9ea3 <unknown>
#12 0x56337fccab01 <unknown>
#13 0x56338019ab3b <unknown>
#14 0x56338019ea21 <unknown>
#15 0x563380181c32 <unknown>
#16 0x56338019f594 <unknown>
#17 0x563380165eef <unknown>
#18 0x5633801c3d98 <unknown>
#19 0x5633801c3f76 <unknown>
#20 0x5633801d4b36 <unknown>
#21 0x7f941f29caa4 <unknown>
#22 0x7f941f329c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_austria_prod?event=eyJhY3Rpb24iOiJzZXRfdXNlcl9hdHRyaWJ1dGUiLCJhY2NvdW50Ijp7ImF0dHJpYnV0ZXMiOnsibGFzdFBpUGFnZSI6eyJ2ZWhpY2xlUEkiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56LmF0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL2NvdXBlL2NsZS9vdmVydmlldy5odG1sIiwidmVoaWNsZUNvZGUiOiJjMjM2IiwidmVoaWNsZUJNIjoiMjM2MyIsInZlaGljbGVQSUhpc3RvcnkiOiIyMzYzIiwidGltZXN0YW1wIjoxNzQ2MDAzOTkyNDA4LCJleHBpcmF0aW9uIjoxMjB9fX0sInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiMTQ0MjUzODU5OC4xNzQ2MDAzOTg3In0sImFub25JZCI6ImE3NjI1Y2UyNTk2ZDM2ZDUifSwic291cmNlIjp7InVybCI6Imh0dHBzOi8vd3d3Lm1lcmNlZGVzLWJlbnouYXQvcGFzc2VuZ2VyY2Fycy9tb2RlbHMvY291cGUvY2xlL292ZXJ2aWV3Lmh0bWwiLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjcxIiwiY29udGVudFpvbmVzIjpbXX0sImNvbnNlbnRzIjpbXSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiIwNDk5NTU3ODc0NjQwODczNSIsImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX19: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x5633801d5cea <unknown>
#1 0x56337fc865f0 <unknown>
#2 0x56337fc6ce86 <unknown>
#3 0x56337fc6b79a <unknown>
#4 0x56337fc6beff <unknown>
#5 0x56337fc6be54 <unknown>
#6 0x56337fc8a7ff <unknown>
#7 0x56337fd2f9aa <unknown>
#8 0x56337fcfd662 <unknown>
#9 0x56337fd23660 <unknown>
#10 0x56337fcfd433 <unknown>
#11 0x56337fcc9ea3 <unknown>
#12 0x56337fccab01 <unknown>
#13 0x56338019ab3b <unknown>
#14 0x56338019ea21 <unknown>
#15 0x563380181c32 <unknown>
#16 0x56338019f594 <unknown>
#17 0x563380165eef <unknown>
#18 0x5633801c3d98 <unknown>
#19 0x5633801c3f76 <unknown>
#20 0x5633801d4b36 <unknown>
#21 0x7f941f29caa4 <unknown>
#22 0x7f941f329c3c <unknown>

ERROR    root:VerifyPersonalizationAndCapture.py:18 ‚ùå Error attaching screenshot to Allure: [Errno 2] No such file or directory: '/home/runner/work/QA-App-Allure/QA-App-Allure/Tests/BFV1_attempt_2.png'