ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_austria_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gb3ZlcnZpZXciLCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjE1NTE4Mjk5MDAuMTc0NTk1ODY1MyJ9LCJhbm9uSWQiOiI0ODNmMjAwYjJmOGVmMWQwIn0sInNvdXJjZSI6eyJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56LmF0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9nbGMvb3ZlcnZpZXcuaHRtbCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNzEiLCJjb250ZW50Wm9uZXMiOltdfSwiY29uc2VudHMiOltdLCJhY2NvdW50Ijp7fSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiI4MTEzMTQwNDEyNTIxOTE1IiwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfX0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.114)
Stacktrace:
#0 0x5587f39f975a <unknown>
#1 0x5587f34ac4b0 <unknown>
#2 0x5587f3492d86 <unknown>
#3 0x5587f349169a <unknown>
#4 0x5587f3491dff <unknown>
#5 0x5587f3491d54 <unknown>
#6 0x5587f34b069f <unknown>
#7 0x5587f355592a <unknown>
#8 0x5587f3523592 <unknown>
#9 0x5587f35495e0 <unknown>
#10 0x5587f3523363 <unknown>
#11 0x5587f34efd63 <unknown>
#12 0x5587f34f09c1 <unknown>
#13 0x5587f39bea6b <unknown>
#14 0x5587f39c2951 <unknown>
#15 0x5587f39a6b62 <unknown>
#16 0x5587f39c34c4 <unknown>
#17 0x5587f398b13f <unknown>
#18 0x5587f39e76f8 <unknown>
#19 0x5587f39e78d6 <unknown>
#20 0x5587f39f85a6 <unknown>
#21 0x7f790e49caa4 <unknown>
#22 0x7f790e529c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_austria_prod?event=eyJpdGVtQWN0aW9uIjoiVmlldyBJdGVtIiwiY2F0YWxvZyI6eyJJdGVtQ2xhc3MiOnsiX2lkIjoib3ZlcnZpZXcifX0sInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiMTU1MTgyOTkwMC4xNzQ1OTU4NjUzIn0sImFub25JZCI6IjQ4M2YyMDBiMmY4ZWYxZDAifSwic291cmNlIjp7InVybCI6Imh0dHBzOi8vd3d3Lm1lcmNlZGVzLWJlbnouYXQvcGFzc2VuZ2VyY2Fycy9tb2RlbHMvc3V2L2dsYy9vdmVydmlldy5odG1sIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI3MSIsImNvbnRlbnRab25lcyI6W119LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJfdG9vbHNFdmVudExpbmtJZCI6IjQwMDk1Nzg2MjQ3NDIzMDQiLCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9fQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.114)
Stacktrace:
#0 0x5587f39f975a <unknown>
#1 0x5587f34ac4b0 <unknown>
#2 0x5587f3492d86 <unknown>
#3 0x5587f349169a <unknown>
#4 0x5587f3491dff <unknown>
#5 0x5587f3491d54 <unknown>
#6 0x5587f34b069f <unknown>
#7 0x5587f355592a <unknown>
#8 0x5587f3523592 <unknown>
#9 0x5587f35495e0 <unknown>
#10 0x5587f3523363 <unknown>
#11 0x5587f34efd63 <unknown>
#12 0x5587f34f09c1 <unknown>
#13 0x5587f39bea6b <unknown>
#14 0x5587f39c2951 <unknown>
#15 0x5587f39a6b62 <unknown>
#16 0x5587f39c34c4 <unknown>
#17 0x5587f398b13f <unknown>
#18 0x5587f39e76f8 <unknown>
#19 0x5587f39e78d6 <unknown>
#20 0x5587f39f85a6 <unknown>
#21 0x7f790e49caa4 <unknown>
#22 0x7f790e529c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_austria_prod?event=eyJhY3Rpb24iOiJQcm9kdWN0IEluZm9ybWF0aW9uIFBhZ2UgLSBvdmVydmlldyAyNTQ2IiwiaXRlbUFjdGlvbiI6IlZpZXcgSXRlbSIsInNvdXJjZSI6eyJwYWdlVHlwZSI6InByb2R1Y3RfaW5mb3JtYXRpb24iLCJsb2NhbGUiOiJkZV9BVCIsImNvbnRlbnRab25lcyI6WyJnbG9iYWxfUElfTkwiLCJwaV9iYW5uZXJfTkwiLCJlcXMtc3BlY2lhbF9OTCJdLCJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56LmF0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9nbGMvb3ZlcnZpZXcuaHRtbCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNzEifSwiZmxhZ3MiOnsicGFnZVZpZXciOnRydWV9LCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjE1NTE4Mjk5MDAuMTc0NTk1ODY1MyJ9LCJhbm9uSWQiOiI0ODNmMjAwYjJmOGVmMWQwIn0sInBlcmZvcm1hbmNlIjp7fSwiZGVidWciOnsiZXhwbGFuYXRpb25zIjp0cnVlfSwiY2F0YWxvZyI6eyJQcm9kdWN0Ijp7Il9pZCI6IjI1NDYiLCJkaW1lbnNpb25zIjp7IkJhdW11c3RlclNob3J0IjpbIjI1NDYiXX19fSwiY29uc2VudHMiOltdLCJhY2NvdW50Ijp7fSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiI4NjY4ODg3NDQ5OTMyODI4In0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.114)
Stacktrace:
#0 0x5587f39f975a <unknown>
#1 0x5587f34ac4b0 <unknown>
#2 0x5587f3492d86 <unknown>
#3 0x5587f349169a <unknown>
#4 0x5587f3491dff <unknown>
#5 0x5587f3491d54 <unknown>
#6 0x5587f34b069f <unknown>
#7 0x5587f355592a <unknown>
#8 0x5587f3523592 <unknown>
#9 0x5587f35495e0 <unknown>
#10 0x5587f3523363 <unknown>
#11 0x5587f34efd63 <unknown>
#12 0x5587f34f09c1 <unknown>
#13 0x5587f39bea6b <unknown>
#14 0x5587f39c2951 <unknown>
#15 0x5587f39a6b62 <unknown>
#16 0x5587f39c34c4 <unknown>
#17 0x5587f398b13f <unknown>
#18 0x5587f39e76f8 <unknown>
#19 0x5587f39e78d6 <unknown>
#20 0x5587f39f85a6 <unknown>
#21 0x7f790e49caa4 <unknown>
#22 0x7f790e529c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_austria_prod?event=eyJhY3Rpb24iOiJzZXRfdXNlcl9hdHRyaWJ1dGUiLCJhY2NvdW50Ijp7ImF0dHJpYnV0ZXMiOnsibGFzdFBpUGFnZSI6eyJ2ZWhpY2xlUEkiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56LmF0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9nbGMvb3ZlcnZpZXcuaHRtbCIsInZlaGljbGVDb2RlIjoieDI1NCIsInZlaGljbGVCTSI6IjI1NDYiLCJ2ZWhpY2xlUElIaXN0b3J5IjoiMjU0NiIsInRpbWVzdGFtcCI6MTc0NTk1ODY1ODAzNSwiZXhwaXJhdGlvbiI6MTIwfX19LCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjE1NTE4Mjk5MDAuMTc0NTk1ODY1MyJ9LCJhbm9uSWQiOiI0ODNmMjAwYjJmOGVmMWQwIn0sInNvdXJjZSI6eyJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56LmF0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9nbGMvb3ZlcnZpZXcuaHRtbCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNzEiLCJjb250ZW50Wm9uZXMiOltdfSwiY29uc2VudHMiOltdLCJfdG9vbHNFdmVudExpbmtJZCI6IjAxMjEwMjA5MjI5NzA1NTk0NCIsImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX19: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.114)
Stacktrace:
#0 0x5587f39f975a <unknown>
#1 0x5587f34ac4b0 <unknown>
#2 0x5587f3492d86 <unknown>
#3 0x5587f349169a <unknown>
#4 0x5587f3491dff <unknown>
#5 0x5587f3491d54 <unknown>
#6 0x5587f34b069f <unknown>
#7 0x5587f355592a <unknown>
#8 0x5587f3523592 <unknown>
#9 0x5587f35495e0 <unknown>
#10 0x5587f3523363 <unknown>
#11 0x5587f34efd63 <unknown>
#12 0x5587f34f09c1 <unknown>
#13 0x5587f39bea6b <unknown>
#14 0x5587f39c2951 <unknown>
#15 0x5587f39a6b62 <unknown>
#16 0x5587f39c34c4 <unknown>
#17 0x5587f398b13f <unknown>
#18 0x5587f39e76f8 <unknown>
#19 0x5587f39e78d6 <unknown>
#20 0x5587f39f85a6 <unknown>
#21 0x7f790e49caa4 <unknown>
#22 0x7f790e529c3c <unknown>

ERROR    root:VerifyPersonalizationAndCapture.py:18 ‚ùå Error attaching screenshot to Allure: [Errno 2] No such file or directory: '/home/runner/work/QA-App-Allure/QA-App-Allure/Tests/BFV1_attempt_2.png'