ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_austria_prod?event=eyJpdGVtQWN0aW9uIjoiVmlldyBJdGVtIiwiY2F0YWxvZyI6eyJJdGVtQ2xhc3MiOnsiX2lkIjoib3ZlcnZpZXcifX0sInVzZXIiOnsiYXR0cmlidXRlcyI6eyJnYUNsaWVudElEIjoiNDQ4MTk1NTQ0LjE3NDU5Njg5MjUifSwiYW5vbklkIjoiMjc1M2FhNmE0NmIwMzVhNyJ9LCJzb3VyY2UiOnsidXJsIjoiaHR0cHM6Ly93d3cubWVyY2VkZXMtYmVuei5hdC9wYXNzZW5nZXJjYXJzL21vZGVscy9zdXYvZy1jbGFzcy9vdmVydmlldy5odG1sIiwidXJsUmVmZXJyZXIiOiIiLCJjaGFubmVsIjoiV2ViIiwiYmVhY29uVmVyc2lvbiI6MTYsImNvbmZpZ1ZlcnNpb24iOiI3MSIsImNvbnRlbnRab25lcyI6W119LCJjb25zZW50cyI6W10sImFjY291bnQiOnt9LCJfdG9vbHNFdmVudExpbmtJZCI6Ijk5NTExNDE2Njk5NDEwNzMiLCJkZWJ1ZyI6eyJleHBsYW5hdGlvbnMiOnRydWV9fQ%3D%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x55eab8ac8cea <unknown>
#1 0x55eab85795f0 <unknown>
#2 0x55eab855fe86 <unknown>
#3 0x55eab855e79a <unknown>
#4 0x55eab855eeff <unknown>
#5 0x55eab855ee54 <unknown>
#6 0x55eab857d7ff <unknown>
#7 0x55eab86229aa <unknown>
#8 0x55eab85f0662 <unknown>
#9 0x55eab8616660 <unknown>
#10 0x55eab85f0433 <unknown>
#11 0x55eab85bcea3 <unknown>
#12 0x55eab85bdb01 <unknown>
#13 0x55eab8a8db3b <unknown>
#14 0x55eab8a91a21 <unknown>
#15 0x55eab8a74c32 <unknown>
#16 0x55eab8a92594 <unknown>
#17 0x55eab8a58eef <unknown>
#18 0x55eab8ab6d98 <unknown>
#19 0x55eab8ab6f76 <unknown>
#20 0x55eab8ac7b36 <unknown>
#21 0x7efc6069caa4 <unknown>
#22 0x7efc60729c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_austria_prod?event=eyJhY3Rpb24iOiJQcm9kdWN0IEluZm9ybWF0aW9uIFBhZ2UgLSBvdmVydmlldyA0NjUyIiwiaXRlbUFjdGlvbiI6IlZpZXcgSXRlbSIsInNvdXJjZSI6eyJwYWdlVHlwZSI6InByb2R1Y3RfaW5mb3JtYXRpb24iLCJsb2NhbGUiOiJkZV9BVCIsImNvbnRlbnRab25lcyI6WyJnbG9iYWxfUElfTkwiLCJwaV9iYW5uZXJfTkwiLCJlcXMtc3BlY2lhbF9OTCJdLCJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56LmF0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9nLWNsYXNzL292ZXJ2aWV3Lmh0bWwiLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjcxIn0sImZsYWdzIjp7InBhZ2VWaWV3Ijp0cnVlfSwidXNlciI6eyJhdHRyaWJ1dGVzIjp7ImdhQ2xpZW50SUQiOiI0NDgxOTU1NDQuMTc0NTk2ODkyNSJ9LCJhbm9uSWQiOiIyNzUzYWE2YTQ2YjAzNWE3In0sInBlcmZvcm1hbmNlIjp7InNka1BhcnNlVGltZSI6MX0sImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX0sImNhdGFsb2ciOnsiUHJvZHVjdCI6eyJfaWQiOiI0NjUyIiwiZGltZW5zaW9ucyI6eyJCYXVtdXN0ZXJTaG9ydCI6WyI0NjUyIl19fX0sImNvbnNlbnRzIjpbXSwiYWNjb3VudCI6e30sIl90b29sc0V2ZW50TGlua0lkIjoiOTczMjE2NTc2NjE3NDUxIn0%3D: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x55eab8ac8cea <unknown>
#1 0x55eab85795f0 <unknown>
#2 0x55eab855fe86 <unknown>
#3 0x55eab855e79a <unknown>
#4 0x55eab855eeff <unknown>
#5 0x55eab855ee54 <unknown>
#6 0x55eab857d7ff <unknown>
#7 0x55eab86229aa <unknown>
#8 0x55eab85f0662 <unknown>
#9 0x55eab8616660 <unknown>
#10 0x55eab85f0433 <unknown>
#11 0x55eab85bcea3 <unknown>
#12 0x55eab85bdb01 <unknown>
#13 0x55eab8a8db3b <unknown>
#14 0x55eab8a91a21 <unknown>
#15 0x55eab8a74c32 <unknown>
#16 0x55eab8a92594 <unknown>
#17 0x55eab8a58eef <unknown>
#18 0x55eab8ab6d98 <unknown>
#19 0x55eab8ab6f76 <unknown>
#20 0x55eab8ac7b36 <unknown>
#21 0x7efc6069caa4 <unknown>
#22 0x7efc60729c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_austria_prod?event=eyJhY3Rpb24iOiJWaXNpdGVkIC0gb3ZlcnZpZXciLCJ1c2VyIjp7ImF0dHJpYnV0ZXMiOnsiZ2FDbGllbnRJRCI6IjQ0ODE5NTU0NC4xNzQ1OTY4OTI1In0sImFub25JZCI6IjI3NTNhYTZhNDZiMDM1YTcifSwic291cmNlIjp7InVybCI6Imh0dHBzOi8vd3d3Lm1lcmNlZGVzLWJlbnouYXQvcGFzc2VuZ2VyY2Fycy9tb2RlbHMvc3V2L2ctY2xhc3Mvb3ZlcnZpZXcuaHRtbCIsInVybFJlZmVycmVyIjoiIiwiY2hhbm5lbCI6IldlYiIsImJlYWNvblZlcnNpb24iOjE2LCJjb25maWdWZXJzaW9uIjoiNzEiLCJjb250ZW50Wm9uZXMiOltdfSwiY29uc2VudHMiOltdLCJhY2NvdW50Ijp7fSwicGVyZm9ybWFuY2UiOnsic2RrUGFyc2VUaW1lIjoxfSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiIyNjYyMjI2Mjc3MTA0NTIzNSIsImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX19: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x55eab8ac8cea <unknown>
#1 0x55eab85795f0 <unknown>
#2 0x55eab855fe86 <unknown>
#3 0x55eab855e79a <unknown>
#4 0x55eab855eeff <unknown>
#5 0x55eab855ee54 <unknown>
#6 0x55eab857d7ff <unknown>
#7 0x55eab86229aa <unknown>
#8 0x55eab85f0662 <unknown>
#9 0x55eab8616660 <unknown>
#10 0x55eab85f0433 <unknown>
#11 0x55eab85bcea3 <unknown>
#12 0x55eab85bdb01 <unknown>
#13 0x55eab8a8db3b <unknown>
#14 0x55eab8a91a21 <unknown>
#15 0x55eab8a74c32 <unknown>
#16 0x55eab8a92594 <unknown>
#17 0x55eab8a58eef <unknown>
#18 0x55eab8ab6d98 <unknown>
#19 0x55eab8ab6f76 <unknown>
#20 0x55eab8ac7b36 <unknown>
#21 0x7efc6069caa4 <unknown>
#22 0x7efc60729c3c <unknown>

ERROR    root:XHRResponseCapturer.py:123 Error capturing response for https://daimleragemea.germany-2.evergage.com/api2/event/mb_austria_prod?event=eyJhY3Rpb24iOiJzZXRfdXNlcl9hdHRyaWJ1dGUiLCJhY2NvdW50Ijp7ImF0dHJpYnV0ZXMiOnsibGFzdFBpUGFnZSI6eyJ2ZWhpY2xlUEkiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56LmF0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9nLWNsYXNzL292ZXJ2aWV3Lmh0bWwiLCJ2ZWhpY2xlQ29kZSI6Inc0NjUiLCJ2ZWhpY2xlQk0iOiI0NjUyIiwidmVoaWNsZVBJSGlzdG9yeSI6IjQ2NTIiLCJ0aW1lc3RhbXAiOjE3NDU5Njg5MzAxNzksImV4cGlyYXRpb24iOjEyMH19fSwidXNlciI6eyJhdHRyaWJ1dGVzIjp7ImdhQ2xpZW50SUQiOiI0NDgxOTU1NDQuMTc0NTk2ODkyNSJ9LCJhbm9uSWQiOiIyNzUzYWE2YTQ2YjAzNWE3In0sInNvdXJjZSI6eyJ1cmwiOiJodHRwczovL3d3dy5tZXJjZWRlcy1iZW56LmF0L3Bhc3NlbmdlcmNhcnMvbW9kZWxzL3N1di9nLWNsYXNzL292ZXJ2aWV3Lmh0bWwiLCJ1cmxSZWZlcnJlciI6IiIsImNoYW5uZWwiOiJXZWIiLCJiZWFjb25WZXJzaW9uIjoxNiwiY29uZmlnVmVyc2lvbiI6IjcxIiwiY29udGVudFpvbmVzIjpbXX0sImNvbnNlbnRzIjpbXSwiX3Rvb2xzRXZlbnRMaW5rSWQiOiIxNDYzMjgwMDY5MTYzODc0OCIsImRlYnVnIjp7ImV4cGxhbmF0aW9ucyI6dHJ1ZX19: Message: unknown error: unhandled inspector error: {"code":-32000,"message":"No resource with given identifier found"}
  (Session info: chrome=135.0.7049.95)
Stacktrace:
#0 0x55eab8ac8cea <unknown>
#1 0x55eab85795f0 <unknown>
#2 0x55eab855fe86 <unknown>
#3 0x55eab855e79a <unknown>
#4 0x55eab855eeff <unknown>
#5 0x55eab855ee54 <unknown>
#6 0x55eab857d7ff <unknown>
#7 0x55eab86229aa <unknown>
#8 0x55eab85f0662 <unknown>
#9 0x55eab8616660 <unknown>
#10 0x55eab85f0433 <unknown>
#11 0x55eab85bcea3 <unknown>
#12 0x55eab85bdb01 <unknown>
#13 0x55eab8a8db3b <unknown>
#14 0x55eab8a91a21 <unknown>
#15 0x55eab8a74c32 <unknown>
#16 0x55eab8a92594 <unknown>
#17 0x55eab8a58eef <unknown>
#18 0x55eab8ab6d98 <unknown>
#19 0x55eab8ab6f76 <unknown>
#20 0x55eab8ac7b36 <unknown>
#21 0x7efc6069caa4 <unknown>
#22 0x7efc60729c3c <unknown>

ERROR    root:VerifyPersonalizationAndCapture.py:18 ‚ùå Error attaching screenshot to Allure: [Errno 2] No such file or directory: '/home/runner/work/QA-App-Allure/QA-App-Allure/Tests/BFV1_attempt_2.png'